SET TIME ZONE 'Asia/Shanghai';

-- Backfill navigation bookmark websites for databases where the original seed
-- migration created groups before item insertion could see those new rows.
WITH desired_items(group_name, name, url, note, icon_url, sort_order) AS (
  VALUES
  ('传统银行', 'NAB Australia - 账户申请', 'https://www.nab.com.au/', 'NAB Australia - 账户申请 属于「传统银行」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.nab.com.au/etc.clientlibs/nab/clientlibs/clientlib-site/resources/images/nab-app-icon-60.png', 0),
  ('传统银行', '1822direkt - 德国银行', 'https://www.1822direkt.de/', '1822direkt - 德国银行 属于「传统银行」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.1822direkt.de/_assets/2e42feddfab07fbfc020b77ea8456016/Favicon/favicon.ico', 1),
  ('传统银行', 'Umweltbank - 德国绿色银行', 'https://www.umweltbank.de/', 'Umweltbank - 德国绿色银行 属于「传统银行」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.umweltbank.de/favicon.ico', 2),
  ('传统银行', 'BPI - 菲律宾银行', 'https://www.bpi.com.ph/', 'BPI - 菲律宾银行 属于「传统银行」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.bpi.com.ph/etc.clientlibs/bpi/clientlibs/clientlib-bpi-ph/resources/BrowserIcon.png', 3),
  ('传统银行', 'BBVA - 德国', 'https://www.bbva.de/', 'BBVA - 德国 属于「传统银行」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.bbva.de/content/dam/library/favicons/favicon-48x48.png', 4),
  ('传统银行', 'Frankfurter Sparkasse', 'https://www.frankfurter-sparkasse.de/', 'Frankfurter Sparkasse 属于「传统银行」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.frankfurter-sparkasse.de/content/dam/myif/sk-frankfurt/work/bilder/icons/favicon1x.ico', 5),
  ('传统银行', 'Tomorrow Bank - 可持续银行', 'https://www.tomorrow.one/en-EU', 'Tomorrow Bank - 可持续银行 属于「传统银行」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://assets.tomorrow.one/images/icons/icon.png', 6),
  ('传统银行', 'HSBC Expat', 'https://www.expat.hsbc.com/', 'HSBC Expat 属于「传统银行」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.expat.hsbc.com/etc.clientlibs/dpws/clientlibs-public/clientlib-site/resources/favicons/apple-touch-icon.png', 7),
  ('传统银行', 'Zempler Bank - KYC', 'https://idv.zemplerbank.com/', 'Zempler Bank - KYC 属于「传统银行」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://idv.zemplerbank.com/favicon.ico', 8),
  ('数字银行 / 新银行 (Neobanks)', 'Neo Bank', 'https://neo-bank.com/', 'Neo Bank 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://neo-bank.com/favicon.ico', 0),
  ('数字银行 / 新银行 (Neobanks)', 'Nickel - 法国', 'https://nickel.eu/fr', 'Nickel - 法国 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://nickel.eu/sites/default/files/favicon_3.ico', 1),
  ('数字银行 / 新银行 (Neobanks)', 'Yuh - 瑞士数字银行', 'https://www.yuh.com/en', 'Yuh - 瑞士数字银行 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.yuh.com/en/wp-content/themes/yuh/assets/images/favicon/apple-icon-57x57.png?v=1781093592', 2),
  ('数字银行 / 新银行 (Neobanks)', 'Tonik Bank - 菲律宾数字银行', 'https://tonikbank.com/', 'Tonik Bank - 菲律宾数字银行 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://tonikbank.com/favicon.ico', 3),
  ('数字银行 / 新银行 (Neobanks)', 'Uno Bank', 'https://www.uno.bank/', 'Uno Bank 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.uno.bank/wp-content/uploads/2022/05/UNO-Favicon.svg', 4),
  ('数字银行 / 新银行 (Neobanks)', 'Clear Bank', 'https://clear.bank/', 'Clear Bank 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://clear.bank/apple-touch-icon.png', 5),
  ('数字银行 / 新银行 (Neobanks)', 'Satchel', 'https://satchel.eu/', 'Satchel 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://satchel.eu/favicon.ico', 6),
  ('数字银行 / 新银行 (Neobanks)', 'Kontist', 'https://kontist.com/', 'Kontist 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://kontist.com/favicon.ico', 7),
  ('数字银行 / 新银行 (Neobanks)', 'Grey', 'https://grey.co/', 'Grey 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/65f95554ca68ea95761a785e_Grey_Icon-32%20(Dark).png', 8),
  ('数字银行 / 新银行 (Neobanks)', 'Aspire', 'https://aspireapp.com/', 'Aspire 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/5ed5b60be1889f546024ada0/6a312738a619f5492f1b88cf_Aspire.png', 9),
  ('数字银行 / 新银行 (Neobanks)', 'Payset', 'https://www.payset.io/', 'Payset 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.payset.io/wp-content/uploads/2025/01/cropped-Payset-fevicon-2-32x32.png', 10),
  ('数字银行 / 新银行 (Neobanks)', 'Conto Mobile', 'https://www.contomobile.com/', 'Conto Mobile 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.contomobile.com/favicons/favicon.png', 11),
  ('数字银行 / 新银行 (Neobanks)', 'Bilderlings', 'https://bilderlings.com/', 'Bilderlings 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://bilderlings.com/th/bilderlings/img/apple-touch-icon-57x57.png', 12),
  ('数字银行 / 新银行 (Neobanks)', 'Olky', 'https://www.olky.eu/en', 'Olky 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.olky.eu/favicons/apple-touch-icon.png?1.0.6', 13),
  ('数字银行 / 新银行 (Neobanks)', 'Moneybase', 'https://www.moneybase.com/', 'Moneybase 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.moneybase.com/favicon.ico', 14),
  ('数字银行 / 新银行 (Neobanks)', 'Finci', 'https://finci.com/', 'Finci 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://finci.com/favicon.ico', 15),
  ('数字银行 / 新银行 (Neobanks)', 'Pink Wallet', 'https://pinkwallet.com/', 'Pink Wallet 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://pinkwallet.com/logo3.png', 16),
  ('数字银行 / 新银行 (Neobanks)', 'Nickel - 德国', 'https://nickel.eu/', 'Nickel - 德国 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://nickel.eu/sites/default/files/favicon_3.ico', 17),
  ('数字银行 / 新银行 (Neobanks)', 'Paytrip - 法国', 'https://www.paytrip.fr/', 'Paytrip - 法国 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.paytrip.fr/wp-content/uploads/2023/04/cropped-Favicon-PayTrip-32x32.png', 18),
  ('数字银行 / 新银行 (Neobanks)', 'Mizen', 'https://www.mizen.eu/', 'Mizen 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/63e67dc9bda8155bd7ae45bb/63ecfdb48619e71ac19759be_Sans%20titre-2.png', 19),
  ('数字银行 / 新银行 (Neobanks)', 'Musc Pay', 'https://www.musc-pay.com/', 'Musc Pay 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/6745d4b07110673c9edb6ab2/67811c47e3153cc1bf9e1645_muscpay-favicon.png', 20),
  ('数字银行 / 新银行 (Neobanks)', 'Noelse', 'https://noelse.com/', 'Noelse 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://noelse.com/wp-content/uploads/2024/12/cropped-noelse-logo-black-app-1-1-32x32.jpg', 21),
  ('数字银行 / 新银行 (Neobanks)', 'Bebunk', 'https://www.bebunk.com/', 'Bebunk 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.bebunk.com/wp-content/uploads/2021/03/bebunk_isotype-512-150x150.png', 22),
  ('数字银行 / 新银行 (Neobanks)', 'VertoFX', 'https://www.vertofx.com/', 'VertoFX 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://verto.co/favicon.ico', 23),
  ('数字银行 / 新银行 (Neobanks)', 'Spush Wallet', 'https://wallet.spush.co.uk/', 'Spush Wallet 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://wallet.spush.co.uk/favicon.ico', 24),
  ('数字银行 / 新银行 (Neobanks)', 'Wire Account', 'https://wireaccount.com/', 'Wire Account 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://wireaccount.com/wp-content/uploads/2023/11/Asset-1-8-150x150.png', 25),
  ('数字银行 / 新银行 (Neobanks)', 'Moneygate', 'https://www.moneygate.com/', 'Moneygate 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.moneygate.com/favicon.png', 26),
  ('数字银行 / 新银行 (Neobanks)', 'Olamit', 'https://olamit.com/', 'Olamit 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://olamit.com/favicon-96x96.png', 27),
  ('数字银行 / 新银行 (Neobanks)', 'CactusPay', 'https://cactuspay.com/', 'CactusPay 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cactuspay.com/favicon.ico', 28),
  ('数字银行 / 新银行 (Neobanks)', 'CFPS', 'https://www.cfps.co/', 'CFPS 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.mbigroup-ms.com/personal/img/auto-insurance-faviconktp.webp', 29),
  ('数字银行 / 新银行 (Neobanks)', 'Banxe', 'https://banxe.com/', 'Banxe 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://banxe.com/favicon.ico', 30),
  ('数字银行 / 新银行 (Neobanks)', 'NovaPay', 'https://novapay.com/en', 'NovaPay 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://novapay.com/favicon.ico', 31),
  ('数字银行 / 新银行 (Neobanks)', 'Kixy', 'https://www.kixy.com/', 'Kixy 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.kixy.com/favicon.ico', 32),
  ('数字银行 / 新银行 (Neobanks)', 'Monitox', 'https://monitox.com/', 'Monitox 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://monitox.com/favicon.ico', 33),
  ('数字银行 / 新银行 (Neobanks)', 'Credits', 'https://credits.com/en', 'Credits 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://credits.com/favicon.ico', 34),
  ('数字银行 / 新银行 (Neobanks)', 'Payz', 'https://payz.com/', 'Payz 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://payz.com/favicon.ico', 35),
  ('数字银行 / 新银行 (Neobanks)', 'Finsei', 'https://finsei.com/', 'Finsei 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://finsei.com/favicon.ico', 36),
  ('数字银行 / 新银行 (Neobanks)', 'Verifo', 'https://verifo.com/', 'Verifo 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://verifo.com/wp-content/themes/verifo/img/favicon/apple-icon-57x57.png', 37),
  ('数字银行 / 新银行 (Neobanks)', 'SikiraPay', 'https://www.sikirapay.eu/', 'SikiraPay 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.sikirapay.eu/wp-content/uploads/2022/01/shield.svg', 38),
  ('数字银行 / 新银行 (Neobanks)', 'BnkPro', 'https://www.bnkpro.com/', 'BnkPro 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.bnkpro.com/favicon.ico', 39),
  ('数字银行 / 新银行 (Neobanks)', 'Yonder', 'https://www.yonder.com/', 'Yonder 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/6209512878b45f39119ebfb5/6232233b2104c2360e4b9deb_YONDER_LOGO_ICON_LIGHT%201%202.png', 40),
  ('数字银行 / 新银行 (Neobanks)', 'Meru', 'https://getmeru.com/', 'Meru 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://getmeru.com/favicon-32x32.png?v=983cedbd2eb8918450213d359a44b58d', 41),
  ('数字银行 / 新银行 (Neobanks)', 'Beans', 'https://www.beansapp.com/', 'Beans 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/642fb32de87a48d3c780840d/66a211c521ef72c69f1c10fe_Ontwerp%20zonder%20titel%20(19)%20(1).jpg', 42),
  ('数字银行 / 新银行 (Neobanks)', 'MoneyJar', 'https://moneyjar.world/', 'MoneyJar 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://moneyjar.world/favicons/favicon-96x96.png', 43),
  ('数字银行 / 新银行 (Neobanks)', 'Moneco', 'https://moneco.app/', 'Moneco 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.moneco.app/favicon.ico', 44),
  ('数字银行 / 新银行 (Neobanks)', 'Spendo', 'https://www.spendo.com/', 'Spendo 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.spendo.com/favicon.ico', 45),
  ('数字银行 / 新银行 (Neobanks)', 'Guava', 'https://myguava.com/', 'Guava 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://myguava.com/favicon.ico', 46),
  ('数字银行 / 新银行 (Neobanks)', 'Plutus', 'https://www.plutus.it/', 'Plutus 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/65fa7967751459f6af9c52f7/693dbc421e97360516b6fba7_Icon%20Square%20(3).png', 47),
  ('数字银行 / 新银行 (Neobanks)', 'Keytom', 'https://keytom.com/', 'Keytom 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/682c9dcfd6f9f908933a7e16/6863aebfbc21e5df0f8d52d2_fav.png', 48),
  ('数字银行 / 新银行 (Neobanks)', 'Cer', 'https://cer.live/', 'Cer 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cer.live/favicon.ico', 49),
  ('数字银行 / 新银行 (Neobanks)', 'Bumba', 'https://bumba.global/en', 'Bumba 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://bumba.global/favicon.ico', 50),
  ('数字银行 / 新银行 (Neobanks)', 'Currenc Australia', 'https://www.currenc.com.au/', 'Currenc Australia 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.currenc.com.au/wp-content/uploads/2018/10/cropped-C-Logo-32x32.png', 51),
  ('数字银行 / 新银行 (Neobanks)', 'HR Bank Offshore', 'https://hrbank.com/', 'HR Bank Offshore 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://hrbank.com/favicon.ico', 52),
  ('数字银行 / 新银行 (Neobanks)', 'Amina Group', 'https://aminagroup.com/', 'Amina Group 属于「数字银行 / 新银行 (Neobanks)」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://aminagroup.com/wp-content/uploads/2024/08/favicon.png', 53),
  ('跨境金融 / 换汇', '跨境支付', 'https://www.kuajinzhifu.com/', '跨境支付 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.kuajinzhifu.com/favicon.ico', 0),
  ('跨境金融 / 换汇', 'Moneycorp', 'https://www.moneycorp.com/en', 'Moneycorp 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.moneycorp.com/Favicon/RedFavicon/apple-icon-57x57.png', 1),
  ('跨境金融 / 换汇', 'Moneycorp Bank', 'https://www.moneycorpbank.com/', 'Moneycorp Bank 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.moneycorpbank.com/favicon.ico', 2),
  ('跨境金融 / 换汇', 'Ludpay', 'https://www.ludpay.com/', 'Ludpay 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/66716f14f2a9dde999912ae6/66719d7743c3233fc663aa84_favicon-32x32.png', 3),
  ('跨境金融 / 换汇', 'Captrex Global', 'https://www.captrexglobal.com/', 'Captrex Global 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.captrexglobal.com/favicon.ico', 4),
  ('跨境金融 / 换汇', 'Finseta', 'https://finseta.com/', 'Finseta 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://finseta.com/wp-content/uploads/2025/12/cropped-BG-3-32x32.png', 5),
  ('跨境金融 / 换汇', 'Weststein Card', 'https://weststeincard.com/', 'Weststein Card 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://weststeincard.com/logo.png', 6),
  ('跨境金融 / 换汇', 'Sogexia', 'https://my.sogexia.com/', 'Sogexia 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://my.sogexia.com/admin/layout2/img/favicon.png?v=20240806', 7),
  ('跨境金融 / 换汇', 'Quant Payment', 'https://client.quantpayment.com/', 'Quant Payment 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://client.quantpayment.com/icons-db1aac84f2b8460cd0566cf745484831/apple-touch-icon-57x57.png', 8),
  ('跨境金融 / 换汇', 'Xportal', 'https://xportal.com/', 'Xportal 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/6527c669d575da173bf65551/680a36b98a1d1b8a6fedc2a8_favicon.png', 9),
  ('跨境金融 / 换汇', 'Altery', 'https://altery.com/', 'Altery 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://altery.com/static/assets/app-icons/icon-32x32.png', 10),
  ('跨境金融 / 换汇', 'AlphaPay', 'https://pay.alphapay.lt/', 'AlphaPay 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://pay.alphapay.lt/favicon.ico', 11),
  ('跨境金融 / 换汇', 'Currency Solutions', 'https://www.currencysolutions.com/', 'Currency Solutions 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.currencysolutions.com/favicons/apple-touch-icon.png', 12),
  ('跨境金融 / 换汇', 'FairFX', 'https://www.fairfx.com/', 'FairFX 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/5f1623efdd7db5c6c3fd4369/5f49164aeaac9c3441e0d7e6_FFX%20Favicon.png', 13),
  ('跨境金融 / 换汇', 'Caxton', 'https://caxton.io/', 'Caxton 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://caxton.io/hubfs/Caxton%20Logo%20-%20Individual%20Letters%20-%20C.png', 14),
  ('跨境金融 / 换汇', 'Quid Global', 'https://quidglobal.com/', 'Quid Global 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://quidglobal.com/wp-content/uploads/2020/09/cropped-favicon_quid-150x150.png', 15),
  ('跨境金融 / 换汇', 'FasterPay', 'https://dashboard.fasterpay.com/', 'FasterPay 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://dashboard.fasterpay.com/favicon.ico', 16),
  ('跨境金融 / 换汇', 'Rutland FX', 'https://rutlandfx.com/', 'Rutland FX 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://rutlandfx.com/wp-content/uploads/2023/03/cropped-Rutland-fx-logo-2019-logomark-isolated-32x32.png', 17),
  ('跨境金融 / 换汇', 'Equals Money', 'https://equalsmoney.com/', 'Equals Money 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://cdn.prod.website-files.com/5f5f51a18621aab5358e77de/6a1d759fb1a98ae253f975d9_Equals%20Favicon.png', 18),
  ('跨境金融 / 换汇', 'TorFX', 'https://online.torfx.com/', 'TorFX 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://online.torfx.com/favicon.ico', 19),
  ('跨境金融 / 换汇', 'YourSafe', 'https://www.yoursafe.com/en', 'YourSafe 属于「跨境金融 / 换汇」，适合查询银行账户、跨境金融、虚拟卡或支付产品信息。', 'https://www.yoursafe.com/favicon.ico', 20),
  ('交易所', 'Binance 币安', 'https://www.binance.com/zh-CN', 'Binance 币安 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.binance.com/favicon.ico', 0),
  ('交易所', 'OKX', 'https://www.okx.com/zh-hans', 'OKX 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.okx.com/cdn/assets/imgs/226/EB771F0EE8994DD5.png', 1),
  ('交易所', 'Bybit', 'https://www.bybit.com/', 'Bybit 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.bybit.com/favicon.ico', 2),
  ('交易所', 'Bitget', 'https://www.bitget.com/zh-CN', 'Bitget 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.bitget.com/baseasset/favicon4.png', 3),
  ('交易所', 'Gate.io', 'https://www.gate.io/zh', 'Gate.io 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.gate.com/favicon.ico', 4),
  ('交易所', 'Kraken', 'https://www.kraken.com/zh-cn', 'Kraken 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.kraken.com/favicon.ico', 5),
  ('交易所', 'Coinbase', 'https://www.coinbase.com/', 'Coinbase 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.coinbase.com/favicon.ico', 6),
  ('交易所', 'Bitfinex', 'https://www.bitfinex.com/', 'Bitfinex 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.bitfinex.com/assets/favicons/bitfinex.ico', 7),
  ('交易所', 'CEX.io', 'https://cex.io/', 'CEX.io 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://cex.io/resources/favicon.ico', 8),
  ('交易所', 'WhiteBit', 'https://whitebit.com/zh-cn', 'WhiteBit 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://whitebit.com/favicon.ico', 9),
  ('交易所', 'Nexo', 'https://nexo.com/zh', 'Nexo 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://nexo.com/favicon.ico?favicon.0s62bpa-jgtdy.ico', 10),
  ('交易所', 'BitMart', 'https://www.bitmart.com/zh-CN', 'BitMart 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.bitmart.com/fav-icon.ico', 11),
  ('交易所', 'HTX (火币)', 'https://www.htx.com/zh-cn', 'HTX (火币) 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://hbg-fed-static-prd.hbfile.net/enhome/favicon.ico?home', 12),
  ('交易所', 'XT.com', 'https://www.xt.com/zh-CN', 'XT.com 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.xt.com/favicon.ico?v=1', 13),
  ('交易所', 'CoinW', 'https://www.coinw.com/', 'CoinW 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.coinw.com/favicon.ico', 14),
  ('交易所', 'ProBit', 'https://www.probit.com/zh-cn', 'ProBit 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.probit.com/favicon.ico', 15),
  ('交易所', 'BiFinance', 'https://www.bifinance.com/', 'BiFinance 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.bifinance.com/favicon.png', 16),
  ('交易所', 'HIBT', 'https://www.hibt.com/', 'HIBT 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.hibt.com/favicon.ico', 17),
  ('交易所', 'LAToken', 'https://latoken.com/zh', 'LAToken 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://latoken.com/favicon/apple-touch-icon.svg', 18),
  ('交易所', 'BigONE', 'https://big.one/cn', 'BigONE 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://b.peatio.com/logos/favicon.ico', 19),
  ('交易所', 'CoinEx', 'https://www.coinex.com/zh-hans', 'CoinEx 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.coinex.com/favicon.svg', 20),
  ('交易所', 'Bitstamp', 'https://www.bitstamp.net/', 'Bitstamp 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.bitstamp.net/favicon.ico', 21),
  ('交易所', 'Bitpanda', 'https://www.bitpanda.com/en', 'Bitpanda 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.bitpanda.com/favicons/apple-touch-icon-image.png', 22),
  ('交易所', 'Rain', 'https://www.rain.com/', 'Rain 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.rain.com/favicon.ico', 23),
  ('交易所', 'Exmo', 'https://exmo.com/zh', 'Exmo 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://cache.exmo.com/199571/_next/static/favicon/57.png', 24),
  ('交易所', 'Bitvavo', 'https://bitvavo.com/en', 'Bitvavo 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://bitvavo.com/favicon.ico', 25),
  ('交易所', 'Blofin', 'https://blofin.com/', 'Blofin 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://blofin.com/favicon.ico', 26),
  ('交易所', 'Neverless', 'https://neverless.com/', 'Neverless 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://neverless.com/apple-touch-icon-57x57_dark.png', 27),
  ('交易所', 'StraitsX', 'https://app.straitsx.com/', 'StraitsX 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://app.straitsx.com/favicon.ico', 28),
  ('交易所', 'Ju.com', 'https://www.ju.com/zh-CN', 'Ju.com 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.ju.com/favicon.ico', 29),
  ('交易所', 'Hotcoin', 'https://www.hotcoin.com/', 'Hotcoin 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.hotcoin.com/images/favicon.ico?v=1781603229419', 30),
  ('交易所', 'BitTap', 'https://www.bittap.com/', 'BitTap 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.bittap.com/favicon.ico', 31),
  ('交易所', 'BitGP', 'https://www.bitgp.com/', 'BitGP 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.bitgp.com/baseasset/favicon5.png', 32),
  ('交易所', 'CoinMetro', 'https://go.coinmetro.com/', 'CoinMetro 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://go.coinmetro.com/favicon/apple-touch-icon.png', 33),
  ('交易所', 'SmartValor', 'https://app.smartvalor.com/', 'SmartValor 属于「交易所」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://app.smartvalor.com/en/assets/favicon.ico', 34),
  ('加密支付 / 电子钱包', 'Payeer', 'https://payeer.com/', 'Payeer 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://payeer.com/favicon.ico', 0),
  ('加密支付 / 电子钱包', 'Airtm', 'https://app.airtm.io/', 'Airtm 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://app.airtm.io/favicon.ico?v=2', 1),
  ('加密支付 / 电子钱包', 'Skrill', 'https://account.skrill.com/', 'Skrill 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://account.skrill.com/assets/skrill/favicon.ico', 2),
  ('加密支付 / 电子钱包', 'ePay', 'https://www.epay.com/', 'ePay 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.epay.com/favicon.ico', 3),
  ('加密支付 / 电子钱包', 'PayPal', 'https://www.paypal.com/', 'PayPal 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.paypalobjects.com/marketing/web/icons/monogram/pp64.png', 4),
  ('加密支付 / 电子钱包', 'Wallex', 'https://app.wallex.global/', 'Wallex 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://app.wallex.global/favicon.ico', 5),
  ('加密支付 / 电子钱包', 'Etana', 'https://crm.etana.com/', 'Etana 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://crm.etana.com/favicon.ico', 6),
  ('加密支付 / 电子钱包', 'CodeGoPay', 'https://codegopay.com/', 'CodeGoPay 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://codegopay.com/favicon.ico', 7),
  ('加密支付 / 电子钱包', 'TropiPay', 'https://www.tropipay.com/', 'TropiPay 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.tropipay.com/favicon.svg', 8),
  ('加密支付 / 电子钱包', 'Neomoon', 'https://online.neomoon.app/', 'Neomoon 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://online.neomoon.app/assets/icon/neomoon.ico', 9),
  ('加密支付 / 电子钱包', 'Uphold', 'https://uphold.com/', 'Uphold 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://uphold.com/favicon.ico', 10),
  ('加密支付 / 电子钱包', 'QvaPay', 'https://qvapay.com/', 'QvaPay 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://www.qvapay.com/favicon.ico', 11),
  ('加密支付 / 电子钱包', 'iFAST GB', 'https://www.ifastgb.com/zh', 'iFAST GB 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://static.ifastgb.com/favicon.ico', 12),
  ('加密支付 / 电子钱包', 'Paysend', 'https://paysend.com/', 'Paysend 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://paysend-design.vercel.app/favicon.svg', 13),
  ('加密支付 / 电子钱包', 'Hurupay', 'https://www.hurupay.com/', 'Hurupay 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://framerusercontent.com/images/CaFxu4wybVO9Nosj8iDtiU5JRU.svg', 14),
  ('加密支付 / 电子钱包', 'SendWirePay', 'https://sendwirepay.com/', 'SendWirePay 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://sendwirepay.com/favicon.ico', 15),
  ('加密支付 / 电子钱包', 'Takenos', 'https://takenos.com/', 'Takenos 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://framerusercontent.com/images/FYYzUhqKhcIJqkJrUqxphUIuqE.png', 16),
  ('加密支付 / 电子钱包', 'Volet', 'https://volet.com/zh', 'Volet 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://volet.com/new/favicon/favicon-96x96.png', 17),
  ('加密支付 / 电子钱包', 'MoneyCollect', 'https://wallet.moneycollect.com/', 'MoneyCollect 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://wallet.moneycollect.com/assets/favicon-ec0a394b.ico', 18),
  ('加密支付 / 电子钱包', 'Jeton', 'https://portal.jeton.com/', 'Jeton 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://portal.jeton.com/favicon/apple-icon-57x57.png', 19),
  ('加密支付 / 电子钱包', 'M-Pay', 'https://portal.m-pay.me/', 'M-Pay 属于「加密支付 / 电子钱包」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://portal.maayanpayments.co.uk/assets/19/gfx/union-favicon.ico', 20),
  ('行情 / 数据', 'CoinMarketCap', 'https://coinmarketcap.com/zh', 'CoinMarketCap 属于「行情 / 数据」，适合查看交易所、加密钱包、支付工具或数字资产数据。', 'https://coinmarketcap.com/apple-touch-icon.png', 0),
  ('eSIM 购买 / 比价', 'Holafly eSIM', 'https://esim.holafly.com/cn', 'Holafly eSIM 属于「eSIM 购买 / 比价」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://media.holafly.com/public/favicon/favicon-96x96.png', 0),
  ('eSIM 购买 / 比价', '9eSIM', 'https://www.9esim.com/zh', '9eSIM 属于「eSIM 购买 / 比价」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.9esim.com/assets/logo-mark.svg', 1),
  ('eSIM 购买 / 比价', 'eSTK', 'https://www.estk.me/', 'eSTK 属于「eSIM 购买 / 比价」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://store.estk.me/favicon.ico', 2),
  ('eSIM 购买 / 比价', 'Wenziwanka eSIM', 'https://shop.wenziwanka.com/', 'Wenziwanka eSIM 属于「eSIM 购买 / 比价」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://shop.wenziwanka.com/favicon.ico', 3),
  ('eSIM 购买 / 比价', 'SwitchSIM', 'https://www.switchesim.com/', 'SwitchSIM 属于「eSIM 购买 / 比价」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.switchesim.com/cdn/shop/files/WechatIMG7.png?crop=center&height=32&v=1727686624&width=32', 4),
  ('eSIM 购买 / 比价', 'XeSIM', 'https://xesim.cc/', 'XeSIM 属于「eSIM 购买 / 比价」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://ueeshop.ly200-cdn.com/u_file/UPBE/UPBE248/2503/19/photo/ico-2.png', 5),
  ('eSIM 购买 / 比价', 'RedTeaGo eSIM', 'https://esim.redteago.com/zh-CN', 'RedTeaGo eSIM 属于「eSIM 购买 / 比价」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://esim.redteago.com/favicon.ico', 6),
  ('eSIM 购买 / 比价', 'SomeGadget x Topsi eSIM', 'https://www.somegadget.shop/en', 'SomeGadget x Topsi eSIM 属于「eSIM 购买 / 比价」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.somegadget.shop/cdn/shop/files/ae_a_a_c_e_e_-3-removebg-preview.png?crop=center&height=32&v=1713099123&width=32', 7),
  ('eSIM 购买 / 比价', 'GoeSIM HK', 'https://goesim.hk/', 'GoeSIM HK 属于「eSIM 购买 / 比价」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://goesim.hk/favicon.ico', 8),
  ('eSIM 购买 / 比价', 'Doc of Card', 'https://docofcard.com/', 'Doc of Card 属于「eSIM 购买 / 比价」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://docofcard.com/wp-content/uploads/2022/12/logo_favicon_250x250.svg', 9),
  ('eSIM 购买 / 比价', 'eSIMDB - eSIM比价', 'https://esimdb.com/', 'eSIMDB - eSIM比价 属于「eSIM 购买 / 比价」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://esimdb.com/favicon.ico', 10),
  ('各国运营商', 'Tello (美国)', 'https://tello.com/', 'Tello (美国) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://tello.com/favicon.ico', 0),
  ('各国运营商', 'Sunrise (瑞士)', 'https://www.sunrise.ch/en', 'Sunrise (瑞士) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.sunrise.ch/eshop/icons/favicon_aurora-48x48.png', 1),
  ('各国运营商', 'Lifecell (乌克兰)', 'https://shop.lifecell.ua/en', 'Lifecell (乌克兰) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://shop.lifecell.ua/favicon.ico', 2),
  ('各国运营商', 'Claro (巴西)', 'https://meuplanoclaro.com.br/', 'Claro (巴西) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://meuplanoclaro.com.br/favicon.ico', 3),
  ('各国运营商', 'Elisa (芬兰)', 'https://elisa.fi/', 'Elisa (芬兰) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://elisa.fi/favicon.ico', 4),
  ('各国运营商', 'SFR (法国)', 'https://www.sfr.fr/', 'SFR (法国) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://static.s-sfr.fr/media/icon-192x192.png', 5),
  ('各国运营商', 'O2 (英国)', 'https://www.o2.co.uk/', 'O2 (英国) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.o2.co.uk/o/o2-theme/images/favicon.ico', 6),
  ('各国运营商', 'EE (英国)', 'https://ee.co.uk/', 'EE (英国) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://ee.co.uk/exp/fep-common-assets/favicons/apple-icon-57x57.png', 7),
  ('各国运营商', 'Vodafone (英国)', 'https://www.vodafone.co.uk/', 'Vodafone (英国) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.vodafone.co.uk/favicon.ico', 8),
  ('各国运营商', 'Vodafone (西班牙)', 'https://www.vodafone.es/', 'Vodafone (西班牙) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.vodafone.es/favicon.ico', 9),
  ('各国运营商', 'Swisscom (瑞士)', 'https://www.swisscom.ch/en', 'Swisscom (瑞士) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.swisscom.ch/errorpages_resp/img/favicon.ico', 10),
  ('各国运营商', 'Vodafone (乌克兰)', 'https://www.vodafone.ua/', 'Vodafone (乌克兰) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.vodafone.ua/favicon.ico', 11),
  ('各国运营商', 'Fizz (加拿大)', 'https://fizz.ca/en', 'Fizz (加拿大) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://fizz.ca/sites/default/files/favicon-96x96.png', 12),
  ('各国运营商', 'Orange (比利时)', 'https://www.orange.be/fr', 'Orange (比利时) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.orange.be/themes/custom/b2cmain/favicon.ico', 13),
  ('各国运营商', 'BASE (比利时)', 'https://www.prd.base.be/en', 'BASE (比利时) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.prd.base.be/favicon.ico', 14),
  ('各国运营商', 'Amaysim (澳大利亚)', 'https://www.amaysim.com.au/', 'Amaysim (澳大利亚) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.amaysim.com.au/etc.clientlibs/amaysim/clientlibs/clientlib-site/resources/meta/favicon.ico', 15),
  ('各国运营商', 'Simyo (西班牙)', 'https://www.simyo.es/', 'Simyo (西班牙) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.simyo.es/favicon.ico?v=20260618130633100', 16),
  ('各国运营商', 'LycaMobile (葡萄牙)', 'https://www.lycamobile.pt/en', 'LycaMobile (葡萄牙) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.lycamobile.pt/favicon.ico', 17),
  ('各国运营商', 'Hot (斯洛文尼亚)', 'https://www.hot.si/', 'Hot (斯洛文尼亚) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.hot.si/favicon-96x96.png', 18),
  ('各国运营商', 'Ooredoo (卡塔尔)', 'https://www.ooredoo.qa/', 'Ooredoo (卡塔尔) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.ooredoo.qa/favicon.ico', 19),
  ('各国运营商', 'Telia (芬兰)', 'https://www.telia.fi/', 'Telia (芬兰) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.telia.fi/dam/jcr:9267c388-5ff5-4b61-b2bd-945049613c46/teliafi-favicon-48x48px.ico', 20),
  ('各国运营商', 'Simyo (荷兰)', 'https://www.simyo.nl/', 'Simyo (荷兰) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.simyo.nl/assets/favicon/apple-touch-icon.png', 21),
  ('各国运营商', 'Sky (英国)', 'https://www.sky.com/', 'Sky (英国) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://static.skyassets.com/favicons/favicon.ico', 22),
  ('各国运营商', 'NOS (葡萄牙)', 'https://www.nos.pt/', 'NOS (葡萄牙) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.nos.pt/etc.clientlibs/nos/clientlibs/clientlib-site/resources/favicons/favicon.ico', 23),
  ('各国运营商', 'Free Mobile (法国)', 'https://mobile.free.fr/', 'Free Mobile (法国) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://mobile.free.fr/static/favicons/apple-touch-icon-152x152.png', 24),
  ('各国运营商', 'T-Mobile (捷克)', 'https://eshop.t-mobile.cz/', 'T-Mobile (捷克) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://eshop.t-mobile.cz/favicon.ico', 25),
  ('各国运营商', 'LMT (拉脱维亚)', 'https://lmt.lmt.lv/en', 'LMT (拉脱维亚) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.lmt.lv/favicon-www/apple-touch-icon.png', 26),
  ('各国运营商', 'Orange (卢森堡)', 'https://www.orange.lu/en', 'Orange (卢森堡) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.orange.lu/media/favicon/default/OrangeFavicon.png', 27),
  ('各国运营商', 'KPN (荷兰)', 'https://www.kpn.com/', 'KPN (荷兰) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.kpn.com/_nuxt_public/assets/images/favicons/favicon.ico', 28),
  ('各国运营商', 'Cuniq (日本)', 'https://www.cuniq.jp/', 'Cuniq (日本) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.cuniq.jp/favicon.ico', 29),
  ('各国运营商', 'Vodafone (葡萄牙)', 'https://www.vodafone.pt/', 'Vodafone (葡萄牙) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.vodafone.pt/content/dam/favicon/apple-touch-icon.png', 30),
  ('各国运营商', 'Vodafone (荷兰)', 'https://www.vodafone.nl/', 'Vodafone (荷兰) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.vodafone.nl/favicon.ico', 31),
  ('各国运营商', 'O2 (德国)', 'https://www.o2online.de/', 'O2 (德国) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.o2online.de/favicon.png', 32),
  ('各国运营商', 'Turkcell (土耳其)', 'https://www.turkcell.com.tr/', 'Turkcell (土耳其) 属于「各国运营商」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://www.turkcell.com.tr/favicon.ico', 33),
  ('eSIM 其他资源', 'eSIM 服务', 'https://16889527.xyz/', 'eSIM 服务 属于「eSIM 其他资源」，适合比较旅行 eSIM、预付费卡、运营商套餐和通信资源。', 'https://16889527.xyz/favicon.ico', 0),
  ('AI 聊天 / 大模型', 'Grok', 'https://grok.com/', 'Grok 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://grok.com/images/favicon.svg', 0),
  ('AI 聊天 / 大模型', 'DeepSeek', 'https://www.deepseek.com/', 'DeepSeek 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://www.deepseek.com/favicon.ico', 1),
  ('AI 聊天 / 大模型', 'Z.ai', 'https://chat.z.ai/', 'Z.ai 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://z-cdn.chatglm.cn/z-ai/static/logo.svg', 2),
  ('AI 聊天 / 大模型', 'Coze 扣子', 'https://www.coze.cn/', 'Coze 扣子 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://lf-coze-web-cdn.coze.cn/obj/coze-web-cn/coze-space/static/favicon2.ico', 3),
  ('AI 聊天 / 大模型', 'Ollama - 本地大模型', 'https://ollama.com/', 'Ollama - 本地大模型 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://ollama.com/public/icon-16x16.png', 4),
  ('AI 聊天 / 大模型', 'AI999999', 'https://ai999999.top/', 'AI999999 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://ai999999.top/favicon-32x32.png', 5),
  ('AI 聊天 / 大模型', '51学AI', 'https://51xueai.chat/', '51学AI 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://51xueai.chat/dj.svg', 6),
  ('AI 聊天 / 大模型', 'AI 中文网', 'https://www.aizws.net/', 'AI 中文网 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://www.aizws.net/favicon.ico', 7),
  ('AI 聊天 / 大模型', 'AI 速管', 'https://www.ai-suguan.com/', 'AI 速管 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://www.ai-suguan.com/favicon.webp', 8),
  ('AI 聊天 / 大模型', 'Hugging Face', 'https://huggingface.co/', 'Hugging Face 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://huggingface.co/favicon.ico', 9),
  ('AI 聊天 / 大模型', 'ModelScope 魔搭', 'https://www.modelscope.cn/', 'ModelScope 魔搭 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://g.alicdn.com/sail-web/maas/2.13.95/favicon/128.ico', 10),
  ('AI 聊天 / 大模型', 'OpenTheRank - AI定价对比', 'https://opentherank.com/', 'OpenTheRank - AI定价对比 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://opentherank.com/favicon.svg', 11),
  ('AI 聊天 / 大模型', 'AI-Bot', 'https://ai-bot.cn/', 'AI-Bot 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://ai-bot.cn/wp-content/uploads/2023/03/ai-bot-square-logo.png', 12),
  ('AI 聊天 / 大模型', 'Zread AI', 'https://zread.ai/', 'Zread AI 属于「AI 聊天 / 大模型」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://zread.ai/favicon.ico', 13),
  ('MCP 服务 / 技能市场', 'Smithery', 'https://smithery.ai/', 'Smithery 属于「MCP 服务 / 技能市场」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://smithery.ai/favicon.ico', 0),
  ('MCP 服务 / 技能市场', 'PulseMCP', 'https://www.pulsemcp.com/', 'PulseMCP 属于「MCP 服务 / 技能市场」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://www.pulsemcp.com/favicon.ico', 1),
  ('MCP 服务 / 技能市场', 'MCP Directory', 'https://mcp.directory/', 'MCP Directory 属于「MCP 服务 / 技能市场」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://mcp.directory/favicon.ico?favicon.d72ac1cb.ico', 2),
  ('MCP 服务 / 技能市场', 'MCP.so', 'https://mcp.so/zh', 'MCP.so 属于「MCP 服务 / 技能市场」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://mcp.so/favicon.ico', 3),
  ('MCP 服务 / 技能市场', 'MCP Market', 'https://mcpmarket.com/zh', 'MCP Market 属于「MCP 服务 / 技能市场」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://mcpmarket.com/favicon.ico', 4),
  ('MCP 服务 / 技能市场', 'MCP Servers', 'https://mcpservers.org/zh-CN', 'MCP Servers 属于「MCP 服务 / 技能市场」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://mcpservers.org/icon.png', 5),
  ('MCP 服务 / 技能市场', 'Skill Store', 'https://skillstore.io/zh-hans', 'Skill Store 属于「MCP 服务 / 技能市场」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://skillstore.io/favicon.svg', 6),
  ('MCP 服务 / 技能市场', 'SkillSMP', 'https://skillsmp.com/zh', 'SkillSMP 属于「MCP 服务 / 技能市场」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://skillsmp.com/favicon.svg', 7),
  ('MCP 服务 / 技能市场', 'Skills Yangsir', 'https://skills.yangsir.net/', 'Skills Yangsir 属于「MCP 服务 / 技能市场」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://skills.yangsir.net/favicon.ico?favicon.0b3bf435.ico', 8),
  ('MCP 服务 / 技能市场', 'XSZN', 'https://xszn.org/zh', 'XSZN 属于「MCP 服务 / 技能市场」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://xszn.org/favicon.ico', 9),
  ('MCP 服务 / 技能市场', 'DevMaster', 'https://devmaster.cn/', 'DevMaster 属于「MCP 服务 / 技能市场」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://devmaster.cn/favicon.ico', 10),
  ('AI 开发 / IDE', 'Claude Code 文档', 'https://docs.claude.com/en', 'Claude Code 文档 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://platform.claude.com/favicon.ico', 0),
  ('AI 开发 / IDE', 'Windsurf IDE', 'https://windsurf.com/', 'Windsurf IDE 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://devin.ai/favicon.ico', 1),
  ('AI 开发 / IDE', 'CodeFlicker', 'https://www.codeflicker.ai/', 'CodeFlicker 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://h2.static.yximgs.com/kcdn/cdn-kcdn112115/ide-login/icons/favicon.ico', 2),
  ('AI 开发 / IDE', 'Verdent AI', 'https://www.verdent.ai/', 'Verdent AI 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://www.verdent.ai/favicon.ico', 3),
  ('AI 开发 / IDE', 'Augment Code', 'https://www.augmentcode.com/', 'Augment Code 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://www.augmentcode.com/favicon.svg', 4),
  ('AI 开发 / IDE', 'OpenCode', 'https://opencode.ai/', 'OpenCode 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://opencode.ai/favicon-96x96-v3.png', 5),
  ('AI 开发 / IDE', 'Kiro', 'https://kiro.dev/', 'Kiro 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://kiro.dev/favicon.ico', 6),
  ('AI 开发 / IDE', 'Qoder', 'https://qoder.com/', 'Qoder 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://img.alicdn.com/imgextra/i3/O1CN01KliT1u1jEq947NlKH_!!6000000004517-55-tps-180-180.svg', 7),
  ('AI 开发 / IDE', 'WithTap', 'https://www.withtap.com/', 'WithTap 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://cdn.prod.website-files.com/63c52465b53a441b76587e8f/6867ff7bacd023651a7a2ff9_favicon.png', 8),
  ('AI 开发 / IDE', 'Zero', 'https://zero.co.uk/', 'Zero 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://zero.co.uk/favicon.ico', 9),
  ('AI 开发 / IDE', 'Bolt.new', 'https://bolt.new/', 'Bolt.new 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://bolt.new/static/favicon.svg', 10),
  ('AI 开发 / IDE', 'Atoms', 'https://atoms.dev/', 'Atoms 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://atoms.dev/favicon.ico', 11),
  ('AI 开发 / IDE', 'Suibian', 'https://suibian.org/', 'Suibian 属于「AI 开发 / IDE」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://suibian.org/favicon.ico?favicon.bbe8aeed.ico', 12),
  ('AI 工具集', 'Tripo3D - AI 3D建模', 'https://studio.tripo3d.ai/', 'Tripo3D - AI 3D建模 属于「AI 工具集」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://studio.tripo3d.ai/favicon.ico', 0),
  ('AI 工具集', 'Hitem3D', 'https://www.hitem3d.ai/zh', 'Hitem3D 属于「AI 工具集」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://hitem3dstatic.zaohaowu.net/FE/static/sparc3d-website/ssr-first-page/favicon.svg', 1),
  ('AI 工具集', 'Bob Translate', 'https://bobtranslate.com/', 'Bob Translate 属于「AI 工具集」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://bobtranslate.com/favicon.ico', 2),
  ('AI 工具集', 'EasyVoice', 'https://easyvoice.ioplus.tech/', 'EasyVoice 属于「AI 工具集」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://easyvoice.ioplus.tech/favicon.ico', 3),
  ('AI 工具集', 'MagicV - AI视频', 'https://magicv.art/zh', 'MagicV - AI视频 属于「AI 工具集」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://magicv.art/favicon.ico?v=2', 4),
  ('AI 工具集', 'BGSub - AI字幕', 'https://zh.bgsub.com/', 'BGSub - AI字幕 属于「AI 工具集」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://zh.bgsub.com/icons/favicon-128x128.png', 5),
  ('AI 工具集', 'eDigitalChoice', 'https://edigitalchoice.com/', 'eDigitalChoice 属于「AI 工具集」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://edigitalchoice.com/fakapp/app-icons/icon-32x32.png', 6),
  ('AI 工具集', 'SkillHub', 'https://skillhub.cn/', 'SkillHub 属于「AI 工具集」，适合试用大模型、AI IDE、MCP 服务或智能工具集合。', 'https://cloudcache.tencent-cloud.com/qcloud/ui/static/other_external_resource/2e166ec6-6f47-4c6d-9915-3f0d75192b56.png', 7),
  ('域名注册', 'Spaceship', 'https://www.spaceship.com/zh', 'Spaceship 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://www.spaceship.com/favicon.ico', 0),
  ('域名注册', 'Regery', 'https://regery.com/en', 'Regery 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://regery.com/favicon.ico', 1),
  ('域名注册', 'GoDaddy', 'https://www.godaddy.com/', 'GoDaddy 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://www.godaddy.com/favicon.ico', 2),
  ('域名注册', 'NameSilo', 'https://www.namesilo.com/', 'NameSilo 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://www.namesilo.com/favicon.ico', 3),
  ('域名注册', 'Namecheap', 'https://www.namecheap.com/', 'Namecheap 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://www.namecheap.com/favicon.ico', 4),
  ('域名注册', 'Dynadot', 'https://www.dynadot.com/zh', 'Dynadot 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://www.dynadot.com/favicon.ico', 5),
  ('域名注册', 'Porkbun', 'https://porkbun.com/', 'Porkbun 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://porkbun.com/images/favicons/apple-icon-57x57.png', 6),
  ('域名注册', 'Cosmotown', 'https://www.cosmotown.com/', 'Cosmotown 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://cosmotown-prod-cdn.s3.amazonaws.com/themes/default/favicon.ico', 7),
  ('域名注册', 'INWX', 'https://www.inwx.com/en', 'INWX 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://www.inwx.com/favicon.ico', 8),
  ('域名注册', 'InternetX', 'https://www.internetx.com/', 'InternetX 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://www.internetx.com/fileadmin/template/img/favicon/apple-touch-icon.png', 9),
  ('域名注册', 'Sav', 'https://marketing.sav.com/zh', 'Sav 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://marketing.sav.com/favicon.ico', 10),
  ('域名注册', 'SmartDomain', 'https://smartdomain.io/zh', 'SmartDomain 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://smartdomain.io/favicon-32x32.png', 11),
  ('域名注册', 'NIC.ua', 'https://nic.ua/en', 'NIC.ua 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://nic.ua/favicon.ico?version=v352', 12),
  ('域名注册', 'NameBeta - 域名比价', 'https://namebeta.com/', 'NameBeta - 域名比价 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://namebeta.com/favicon.ico', 13),
  ('域名注册', 'TLD List', 'https://zh-hant.tld-list.com/', 'TLD List 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://zh-hant.tld-list.com/favicon.ico', 14),
  ('域名注册', 'Nazhumi - 域名比价', 'https://www.nazhumi.com/', 'Nazhumi - 域名比价 属于「域名注册」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://www.nazhumi.com/favicon.ico', 15),
  ('免费域名', 'GetFreeDomain', 'https://www.getfreedomain.name/', 'GetFreeDomain 属于「免费域名」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://www.getfreedomain.name/logo.svg', 0),
  ('免费域名', 'FreeDomain One', 'https://freedomain.one/', 'FreeDomain One 属于「免费域名」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://freedomain.one/site/fd/images/fd-logo.png', 1),
  ('免费域名', 'Dynu', 'https://www.dynu.com/zh-CN', 'Dynu 属于「免费域名」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://www.dynu.com/favicon.ico', 2),
  ('免费域名', 'YDNS', 'https://ydns.io/', 'YDNS 属于「免费域名」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://ydns.io/assets/img/apple-touch-icon.png', 3),
  ('免费域名', 'Zone.id', 'https://my.zone.id/', 'Zone.id 属于「免费域名」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://my.zone.id/subzoneid.png', 4),
  ('免费域名', 'Domain DigitalPlat', 'https://dash.domain.digitalplat.org/', 'Domain DigitalPlat 属于「免费域名」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://dash.domain.digitalplat.org/favicon.ico', 5),
  ('DNS / CDN', 'Cloudflare', 'https://dash.cloudflare.com/', 'Cloudflare 属于「DNS / CDN」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://dash.cloudflare.com/favicon.ico', 0),
  ('DNS / CDN', 'ClouDNS', 'https://www.cloudns.net/', 'ClouDNS 属于「DNS / CDN」，适合管理域名注册、免费域名、DNS、CDN 和基础托管服务。', 'https://www.cloudns.net/images/web/favicon.gif', 1),
  ('VPS 提供商', 'Hetzner', 'https://www.hetzner.com/', 'Hetzner 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.hetzner.com/_resources/themes/hetzner/images/favicons/favicon.ico', 0),
  ('VPS 提供商', 'Contabo', 'https://contabo.com/', 'Contabo 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://cdn.contabo.com/favicon.ico', 1),
  ('VPS 提供商', 'UpCloud', 'https://upcloud.com/', 'UpCloud 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://upcloud.com/favicon.ico', 2),
  ('VPS 提供商', 'Scaleway', 'https://www.scaleway.com/en', 'Scaleway 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.scaleway.com/favicon/website/favicon.svg', 3),
  ('VPS 提供商', 'Time4VPS', 'https://www.time4vps.com/', 'Time4VPS 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.time4vps.com/favicon.ico', 4),
  ('VPS 提供商', 'RackNerd', 'https://www.racknerd.com/', 'RackNerd 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.racknerd.com/favicon.png', 5),
  ('VPS 提供商', 'Vultr', 'https://my.vultr.com/', 'Vultr 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://console.vultr.com/apple-touch-icon.png?v=1', 6),
  ('VPS 提供商', 'Leaseweb', 'https://www.leaseweb.com/en', 'Leaseweb 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.leaseweb.com/favicon.ico', 7),
  ('VPS 提供商', 'OVHcloud', 'https://www.ovhcloud.com/en', 'OVHcloud 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.ovhcloud.com/favicon.ico', 8),
  ('VPS 提供商', 'IONOS', 'https://www.ionos.de/', 'IONOS 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.ionos.de/favicon.ico?v2', 9),
  ('VPS 提供商', 'Strato', 'https://www.strato.de/', 'Strato 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.strato.de/favicon.ico', 10),
  ('VPS 提供商', 'DigVPS', 'https://digvps.com/', 'DigVPS 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://digvps.com/favicon.png', 11),
  ('VPS 提供商', 'Prolxy', 'https://www.prolxy.com/', 'Prolxy 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.prolxy.com/favicon.ico', 12),
  ('VPS 提供商', 'UQIDC', 'https://www.uqidc.com/', 'UQIDC 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.uqidc.com/themes/web/Lolipa/assets/images/favicon.png', 13),
  ('VPS 提供商', 'HostFe', 'https://hostfe.com/', 'HostFe 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://hostfe.com/ico/android-chrome-512x512.png', 14),
  ('VPS 提供商', 'SZHDY', 'https://www.szhdy.com/', 'SZHDY 属于「VPS 提供商」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.szhdy.com/themes/web/www/upload/local68dd3c919a863.png', 15),
  ('云平台', 'Vercel', 'https://vercel.com/', 'Vercel 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://assets.vercel.com/image/upload/q_auto/front/favicon/vercel/favicon.ico', 0),
  ('云平台', 'Netlify', 'https://www.netlify.com/', 'Netlify 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.netlify.com/favicon/favicon.ico', 1),
  ('云平台', 'Fly.io', 'https://fly.io/', 'Fly.io 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://fly.io/phx/ui/images/favicon/favicon-595d1312b35dfe32838befdf8505515e.ico?vsn=d', 2),
  ('云平台', 'Render', 'https://render.com/', 'Render 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://render.com/icon.svg?e6fbdd2e217c0064', 3),
  ('云平台', 'Zeabur', 'https://zeabur.com/', 'Zeabur 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://zeabur.com/favicon-32x32.png', 4),
  ('云平台', '腾讯云', 'https://cloud.tencent.com/', '腾讯云 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://cloudcache.tencent-cloud.com/qcloud/favicon.ico?t=201902181234', 5),
  ('云平台', '腾讯云国际', 'https://www.tencentcloud.com/zh', '腾讯云国际 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.tencentcloud.com/favicon.ico?t=201902181234', 6),
  ('云平台', '京东云', 'https://www.jdcloud.com/', '京东云 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://img1.jcloudcs.com/portal/favicon.ico', 7),
  ('云平台', '宝塔面板', 'https://www.bt.cn/', '宝塔面板 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.bt.cn/favicon.ico', 8),
  ('云平台', 'Hostinger', 'https://www.hostinger.com/hk', 'Hostinger 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.hostinger.com/favicon.ico', 9),
  ('云平台', 'Hostinger', 'https://www.hostinger.com/', 'Hostinger 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://www.hostinger.com/favicon.ico', 10),
  ('云平台', 'X10Hosting', 'https://x10hosting.com/', 'X10Hosting 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://x10hosting.com/favicon.ico', 11),
  ('云平台', 'Aiven', 'https://aiven.io/', 'Aiven 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://aiven.io/favicons/apple-touch-icon.png', 12),
  ('云平台', 'LeanCloud', 'https://console.leancloud.app/', 'LeanCloud 属于「云平台」，适合比较 VPS、云平台、部署服务和服务器托管资源。', 'https://console.leancloud.app/favicon.ico', 13),
  ('VPN 与代理', '梨花狮 VPN', 'https://lihuashivpn.com/', '梨花狮 VPN 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://lihuashivpn.com/favicon.ico', 0),
  ('VPN 与代理', '666 VPN', 'https://666.xnphf.cn/', '666 VPN 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://666.xnphf.cn/favicon.ico', 1),
  ('VPN 与代理', 'HT VPN', 'https://ht.idsduf.com/', 'HT VPN 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://ht.idsduf.com/favicon.ico', 2),
  ('VPN 与代理', 'VPN 服务', 'https://xn--mes358acgm99l.com/', 'VPN 服务 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://xn--mes358acgm99l.com/favicon.ico', 3),
  ('VPN 与代理', 'VYY VPN', 'https://vyy.idsduf.com/', 'VYY VPN 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://vyy.idsduf.com/favicon.ico', 4),
  ('VPN 与代理', 'VPN 服务', 'https://xn--66tw07h.com/', 'VPN 服务 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://xn--66tw07h.com/favicon.ico', 5),
  ('VPN 与代理', 'ikuajings VPN', 'https://www.ikuajings.com/', 'ikuajings VPN 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://www.ikuajings.com/favicon.ico', 6),
  ('VPN 与代理', 'VPN 服务', 'https://xn--9kqs15ei25a.xyz/', 'VPN 服务 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://xn--9kqs15ei25a.xyz/css/favicon.ico', 7),
  ('VPN 与代理', 'Starlink Cloud', 'https://was.starlinkcloud.cc/', 'Starlink Cloud 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://was.starlinkcloud.cc/images/logo.png', 8),
  ('VPN 与代理', 'VPN 服务', 'http://xn--123-vd0gw60p.com/', 'VPN 服务 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://kiss.wikinyyds.com/favicon.ico', 9),
  ('VPN 与代理', 'Starbebo', 'https://1.starbebo.sbs/', 'Starbebo 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://1.starbebo.sbs/favicon.ico', 10),
  ('VPN 与代理', '665353 VPN', 'https://user.665353.xyz/', '665353 VPN 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://user.665353.xyz/theme/shower/assets/images/logo/favicon.png', 11),
  ('VPN 与代理', 'SuperBed', 'https://www.superbed.cc/', 'SuperBed 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://www.superbed.cc/favicon.ico', 12),
  ('VPN 与代理', 'SuperBed CN', 'https://www.superbed.cn/', 'SuperBed CN 是代理或网络访问相关入口，适合整理网络连接、线路或隐私访问资源。', 'https://www.superbed.cn/favicon.ico', 13),
  ('云存储', 'AkiraBox', 'https://akirabox.com/', 'AkiraBox 是云存储入口，适合管理网盘、文件同步、备份和在线存储服务。', 'https://akirabox.com/favicon.ico', 0),
  ('云存储', 'pCloud', 'http://pcloud.com/', 'pCloud 是云存储入口，适合管理网盘、文件同步、备份和在线存储服务。', 'https://pcdn-www.pcloud.com/ZWxMD/images/favicons/favicon-16x16.png', 1),
  ('云存储', 'Drime Cloud', 'https://drime.cloud/', 'Drime Cloud 是云存储入口，适合管理网盘、文件同步、备份和在线存储服务。', 'https://framerusercontent.com/images/LZNCznA6dwo81JAN24sbVeuI.png', 2),
  ('云存储', 'MEGA', 'https://mega.nz/', 'MEGA 是云存储入口，适合管理网盘、文件同步、备份和在线存储服务。', 'https://mega.nz/favicon.ico?v=3', 3),
  ('云存储', 'BlazeB2 - Cloudflare R2', 'https://blazeb2.js.org/', 'BlazeB2 - Cloudflare R2 是云存储入口，适合管理网盘、文件同步、备份和在线存储服务。', 'https://blazeb2.js.org/favicon.ico', 4),
  ('国际邮箱', 'Gmail', 'https://mail.google.com/', 'Gmail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://accounts.google.com/favicon.ico', 0),
  ('国际邮箱', 'Outlook', 'https://outlook.live.com/', 'Outlook 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://outlook.live.com/mail/favicon.ico', 1),
  ('国际邮箱', 'Yahoo Mail', 'https://mail.yahoo.com/', 'Yahoo Mail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://s.yimg.com/cv/apiv2/default/hp/favicon.ico', 2),
  ('国际邮箱', 'AOL Mail', 'https://mail.aol.com/', 'AOL Mail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://s.yimg.com/nq/nr/img/aol_favicon_afYliGTEgGH181tujkoqqgnZUo0MWJfO0YO89iYimHY_v1.ico', 3),
  ('国际邮箱', 'Zoho Mail', 'https://mail.zoho.com/', 'Zoho Mail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.zoho.com/favicon.ico', 4),
  ('国际邮箱', 'Proton Mail', 'https://account.proton.me/zh-cn', 'Proton Mail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://account.proton.me/assets/favicon.ico', 5),
  ('国际邮箱', 'Yandex Mail', 'https://mail.yandex.com/', 'Yandex Mail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://passport.yandex.com/favicon.ico', 6),
  ('国际邮箱', 'GMX', 'https://www.gmx.com/', 'GMX 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://s.uicdn.com/mailint/10.203.0/assets/favicon_gmxcom.ico', 7),
  ('国际邮箱', 'Mail.com', 'https://www.mail.com/', 'Mail.com 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://s.uicdn.com/mailint/10.203.0/assets/favicon.ico', 8),
  ('国际邮箱', 'Web.de', 'https://web.de/', 'Web.de 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://img.ui-portal.de/webde/favicon.ico', 9),
  ('国际邮箱', '5x2', 'https://5x2.de/', '5x2 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://5x2.de/assets/images/core-img/fav.ico', 10),
  ('国际邮箱', 'X-Mail', 'https://x-mail.plus/', 'X-Mail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://x-mail.plus/sitefiles/favicon/favicon-32.svg', 11),
  ('国际邮箱', 'Mail.de', 'https://mail.de/de', 'Mail.de 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.de/apple-touch-icon.png', 12),
  ('国际邮箱', 'Mail.co.uk', 'https://mail.co.uk/en', 'Mail.co.uk 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.co.uk/apple-touch-icon.png', 13),
  ('国际邮箱', 'Atomic Mail', 'https://atomicmail.io/', 'Atomic Mail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://cdn.prod.website-files.com/6673e05f71ed2b08b5404a28/667b22bfb4576291d6a646eb_favicon.png', 14),
  ('国际邮箱', 'Firemail', 'https://firemail.de/', 'Firemail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://firemail.de/favicon.ico', 15),
  ('国际邮箱', 'Eclipso', 'https://www.eclipso.ch/', 'Eclipso 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.eclipso.ch/apple-touch-icon.png', 16),
  ('国际邮箱', 'Murena', 'https://murena.io/', 'Murena 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://murena.io/favicon.ico', 17),
  ('国际邮箱', 'Disroot', 'https://webmail.disroot.org/', 'Disroot 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://webmail.disroot.org/static.php/skins/disroot/images/favicon.ico?s=1773954117', 18),
  ('国际邮箱', 'Infomaniak', 'https://manager.infomaniak.com/', 'Infomaniak 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://manager.infomaniak.com/favicon.ico', 19),
  ('国际邮箱', 'Freemail (匈牙利)', 'https://accounts.freemail.hu/', 'Freemail (匈牙利) 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://accounts.freemail.hu/a/api/favicon.ico', 20),
  ('国际邮箱', 'SZN (捷克)', 'https://login.szn.cz/', 'SZN (捷克) 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://login.szn.cz/static/img/favicon.ico', 21),
  ('国际邮箱', 'Onet (波兰)', 'https://poczta.onet.pl/', 'Onet (波兰) 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://konto.onet.pl/favicon.ico', 22),
  ('国际邮箱', 'O2 (波兰)', 'https://poczta.o2.pl/', 'O2 (波兰) 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://pocztanh.wpcdn.pl/pocztanh/login/7.37.0-dev.feat-prpp-25860.s015.15/images/o2/favicon.png', 23),
  ('国际邮箱', 'WP (波兰)', 'https://poczta.wp.pl/', 'WP (波兰) 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://pocztanh.wpcdn.pl/pocztanh/login/7.37.0/images/wp/favicon.ico', 24),
  ('国际邮箱', 'Mail.bg (保加利亚)', 'https://mail.bg/', 'Mail.bg (保加利亚) 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.bg/favicon.ico', 25),
  ('国际邮箱', 'Sapo (葡萄牙)', 'https://mail.sapo.pt/', 'Sapo (葡萄牙) 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://assets.web.sapo.io/sapologos/favicon/mail.sapo.pt/favicon.ico', 26),
  ('国际邮箱', 'Daum Mail (韩国)', 'https://mail.daum.net/', 'Daum Mail (韩国) 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://logins.daum.net/favicon.ico?ver=260521015934', 27),
  ('国际邮箱', 'Kakao Mail (韩国)', 'https://mail.kakao.com/', 'Kakao Mail (韩国) 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.kakao.com/favicon.ico', 28),
  ('国际邮箱', 'Inbox.lv', 'https://www.inbox.lv/', 'Inbox.lv 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.inbox.lv/favicon.ico', 29),
  ('国际邮箱', 'Mail.ee', 'https://www.mail.ee/', 'Mail.ee 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.mail.ee/assets/com/img/icons/portal_ee/favicon.ico?e23489e9221df3c', 30),
  ('国际邮箱', 'Inbox.lt', 'https://www.inbox.lt/', 'Inbox.lt 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.inbox.lt/favicon.ico', 31),
  ('国际邮箱', 'Inbox.la', 'https://www.inbox.la/', 'Inbox.la 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.inbox.la/assets/com/img/icons/mail/favicon.ico?e39c09799f5320f', 32),
  ('国际邮箱', 'Inbox.qa', 'https://www.inbox.qa/', 'Inbox.qa 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.inbox.qa/assets/com/img/icons/mail/favicon.ico?e23489e9221df3c', 33),
  ('国际邮箱', 'Inbox.pk', 'https://www.inbox.pk/', 'Inbox.pk 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.inbox.pk/assets/com/img/icons/mail/favicon.ico?e23489e9221df3c', 34),
  ('国际邮箱', 'Inbox.vg', 'https://login.inbox.vg/', 'Inbox.vg 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://login.inbox.vg/assets/com/img/icons/mail/favicon.ico?09ad5f7a241eb5c', 35),
  ('国际邮箱', 'Mail.ru', 'https://e.mail.ru/', 'Mail.ru 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://imgs2.imgsmail.ru/static/logo/rebranding/logo_favicon.png', 36),
  ('国际邮箱', 'VK Mail', 'https://vk.mail.ru/', 'VK Mail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://vk.mail.ru/favicon.ico', 37),
  ('国际邮箱', 'Rambler Mail', 'https://mail.rambler.ru/', 'Rambler Mail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.rambler.su/000500/i/icons/favicon.ico', 38),
  ('国际邮箱', 'Sibnet Mail', 'https://mail.sibnet.ru/', 'Sibnet Mail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.sibnet.ru/favicon.ico', 39),
  ('国际邮箱', 'Xmail', 'https://xmail.net/', 'Xmail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://xmail.net/favicon.ico', 40),
  ('国际邮箱', 'Ukr.net', 'https://accounts.ukr.net/', 'Ukr.net 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://accounts.ukr.net/login/assets/favicon.png', 41),
  ('国际邮箱', 'Aikq', 'https://www.aikq.de/', 'Aikq 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.aikq.de/favicon.ico', 42),
  ('国际邮箱', 'Mailo', 'https://www.mailo.com/', 'Mailo 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.mailo.com/favicon/favicon.ico', 43),
  ('国际邮箱', 'Vodafone Mail', 'https://mail.vodafone.de/', 'Vodafone Mail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.vodafone.de/assets/favicon-32-BqZ9QQxZ.png', 44),
  ('国际邮箱', 'Tinkmail - 临时邮箱', 'https://tinkmail.me/', 'Tinkmail - 临时邮箱 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://tinkmail.me/favicon.png', 45),
  ('国际邮箱', 'Astermail', 'https://astermail.org/', 'Astermail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://astermail.org/favicon.ico', 46),
  ('国际邮箱', 'Pissmail', 'https://pissmail.com/', 'Pissmail 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://pissmail.com/favicon.ico', 47),
  ('国际邮箱', 'Mailum', 'https://mailum.com/', 'Mailum 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mailum.com/mailum.svg', 48),
  ('国际邮箱', 'iRedMail - 自建邮箱', 'https://iredmail.org/', 'iRedMail - 自建邮箱 属于「国际邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://iredmail.org/assets/images/favicon.ico', 49),
  ('国内邮箱', 'QQ 邮箱', 'https://wx.mail.qq.com/', 'QQ 邮箱 属于「国内邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://res.wx.qq.com/t/webmail/webmail/res/static/images/base/style/favicon/qqmail_favicon_16h.bc34dcb.png', 0),
  ('国内邮箱', '163 邮箱', 'https://mail.163.com/', '163 邮箱 属于「国内邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.163.com/favicon.ico', 1),
  ('国内邮箱', '126 邮箱', 'https://www.126.com/', '126 邮箱 属于「国内邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.163.com/favicon.ico', 2),
  ('国内邮箱', 'Yeah.net', 'https://yeah.net/', 'Yeah.net 属于「国内邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.163.com/favicon.ico', 3),
  ('国内邮箱', '阿里云邮箱', 'https://mail.aliyun.com/', '阿里云邮箱 属于「国内邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://mail.aliyun.com/favicon.ico', 4),
  ('国内邮箱', '新浪邮箱', 'https://m1.mail.sina.com.cn/', '新浪邮箱 属于「国内邮箱」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://login.sina.com.cn/favicon.ico', 5),
  ('邮箱工具 / 签名', 'Engine Mailer', 'https://www.enginemailer.com/', 'Engine Mailer 属于「邮箱工具 / 签名」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.enginemailer.com/Content/favicon/favicon.ico', 0),
  ('邮箱工具 / 签名', '邮件签名生成器', 'https://www.mail-signatures.com/', '邮件签名生成器 属于「邮箱工具 / 签名」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.mail-signatures.com/favicon.ico', 1),
  ('邮箱工具 / 签名', 'BeeFree 邮件模板', 'https://beefree.io/', 'BeeFree 邮件模板 属于「邮箱工具 / 签名」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://cdn.prod.website-files.com/64942e7300c2898fa7449d1c/64bf8306b12d7b7194320ef0_Beefree-favicon.png', 2),
  ('邮箱工具 / 签名', 'Mailmodo 模板', 'https://www.mailmodo.com/', 'Mailmodo 模板 属于「邮箱工具 / 签名」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.mailmodo.com/favicon.ico', 3),
  ('邮箱工具 / 签名', 'Stripo 邮件模板', 'https://stripo.email/', 'Stripo 邮件模板 属于「邮箱工具 / 签名」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://live-content-worker.stripocdn.email/static-assets/favicon.png', 4),
  ('邮箱工具 / 签名', 'Notion Mail', 'https://www.notion.com/', 'Notion Mail 属于「邮箱工具 / 签名」，适合管理邮箱账号、邮件服务、邮箱工具或邮件签名。', 'https://www.notion.com/front-static/favicon.ico', 5),
  ('短信验证码平台', 'SMSPool', 'https://www.smspool.net/', 'SMSPool 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://www.smspool.net/favicon.ico', 0),
  ('短信验证码平台', 'SMS-Activate', 'https://sms-activate.guru/cn', 'SMS-Activate 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://sms-activate.guru/favicon.ico', 1),
  ('短信验证码平台', '5SIM', 'https://5sim.net/zh', '5SIM 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://5sim.net/favicon.ico', 2),
  ('短信验证码平台', 'OnlineSIM', 'https://onlinesim.io/', 'OnlineSIM 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://onlinesim.io/favicon.ico', 3),
  ('短信验证码平台', 'SMS-Man', 'https://sms-man.com/cn', 'SMS-Man 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://sms-man.com/favicon.ico', 4),
  ('短信验证码平台', 'GrizzlySMS', 'https://grizzlysms.com/cn', 'GrizzlySMS 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://grizzlysms.com/favicon.ico', 5),
  ('短信验证码平台', 'TigerSMS', 'https://tiger-sms.com/cn', 'TigerSMS 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://tiger-sms.com/favicon.ico', 6),
  ('短信验证码平台', 'Daputao 大葡萄', 'https://daputao.me/', 'Daputao 大葡萄 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://daputao.me/favicon.ico', 7),
  ('短信验证码平台', '2024SMS', 'https://2024sms.com/', '2024SMS 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://2024sms.com/123.ico', 8),
  ('短信验证码平台', 'AMZS66', 'https://www.amzs66.com/', 'AMZS66 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://www.amzs66.com/favicon.ico', 9),
  ('短信验证码平台', 'YM158', 'https://www.ym158.com/', 'YM158 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://www.ym158.com/favicon.ico', 10),
  ('短信验证码平台', '很多号', 'https://www.henduohao.com/', '很多号 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://www.henduohao.com/favicon.ico', 11),
  ('短信验证码平台', 'Virtual Mall', 'https://www.virtual-mall.vip/', 'Virtual Mall 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://www.virtual-mall.vip/favicon.ico', 12),
  ('短信验证码平台', '飞鸡鸡', 'https://www.feijiji.com/', '飞鸡鸡 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://www.feijiji.com/favicon.ico', 13),
  ('短信验证码平台', '账号鸭', 'https://www.zhanghaoya.com/', '账号鸭 是短信验证码平台入口，适合临时收码、注册验证和号码资源比较。', 'https://www.zhanghaoya.com/favicon.png', 14),
  ('图标', 'Icon Kitchen', 'https://icon.kitchen/', 'Icon Kitchen 属于「图标」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://icon.kitchen/favicon.ico', 0),
  ('图标', 'YesIcon', 'https://yesicon.app/', 'YesIcon 属于「图标」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://yesicon.app/favicon.ico', 1),
  ('图标', 'IconBuddy', 'https://iconbuddy.com/', 'IconBuddy 属于「图标」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://iconbuddy.com/favicon.ico', 2),
  ('图标', 'Icons8', 'https://icons8.com/', 'Icons8 属于「图标」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://icons8.com/favicon.ico', 3),
  ('图标', 'Lucide', 'https://lucide.dev/', 'Lucide 属于「图标」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://lucide.dev/favicon.ico', 4),
  ('图标', 'Ionicons', 'https://ionic.io/', 'Ionicons 属于「图标」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://ionic.io/apple-icon-57x57.png', 5),
  ('图标', 'Remix Icon', 'https://remixicon.com/', 'Remix Icon 属于「图标」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://remixicon.com/favicon.ico', 6),
  ('图标', 'XIcons', 'https://www.xicons.org/', 'XIcons 属于「图标」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://www.xicons.org/favicon.svg', 7),
  ('图标', 'ItsHover Icons', 'https://www.itshover.com/', 'ItsHover Icons 属于「图标」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://www.itshover.com/favicon.ico?favicon.9c96363b.ico', 8),
  ('图标', 'FontLogo', 'https://fontlogo.site/', 'FontLogo 属于「图标」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://fontlogo.site/favicon.png', 9),
  ('UI 组件 / 设计系统', 'Uiverse - CSS 组件社区', 'https://uiverse.io/', 'Uiverse - CSS 组件社区 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://uiverse.io/favicon.ico', 0),
  ('UI 组件 / 设计系统', 'ReactBits', 'https://reactbits.dev/', 'ReactBits 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://reactbits.dev/favicon.ico', 1),
  ('UI 组件 / 设计系统', 'Magic UI', 'https://magicui.design/', 'Magic UI 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://magicui.design/favicon.ico', 2),
  ('UI 组件 / 设计系统', 'Spark UI', 'https://spark-ui.dev/', 'Spark UI 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://spark-ui.dev/icon.png', 3),
  ('UI 组件 / 设计系统', 'VueBits', 'https://vue-bits.dev/', 'VueBits 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://vue-bits.dev/favicon.ico', 4),
  ('UI 组件 / 设计系统', 'FinalUI', 'https://finalui.com/', 'FinalUI 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://assets.ycodeapp.com/assets/app119042/favicons/7ePAuOd4OyHHarv1y8kArcXu9K5oVpNmGQPpZ8tL.png', 5),
  ('UI 组件 / 设计系统', 'UI Layouts', 'https://www.ui-layouts.com/', 'UI Layouts 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://www.ui-layouts.com/favicon-16x16.png', 6),
  ('UI 组件 / 设计系统', 'Refero Design', 'https://refero.design/', 'Refero Design 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://refero.design/favicon.ico', 7),
  ('UI 组件 / 设计系统', 'Refero Styles', 'https://styles.refero.design/', 'Refero Styles 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://styles.refero.design/favicon.ico?favicon.0dc-sx-~wo8io.ico', 8),
  ('UI 组件 / 设计系统', 'COSS UI', 'https://coss.com/', 'COSS UI 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://coss.com/ui/favicon.ico?favicon.0o7l7iug-qg2i.ico', 9),
  ('UI 组件 / 设计系统', 'Mantine v8', 'https://v8.mantine.dev/', 'Mantine v8 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://v8.mantine.dev/favicon.svg', 10),
  ('UI 组件 / 设计系统', 'GPUI Component', 'https://longbridge.github.io/', 'GPUI Component 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://longbridge.github.io/favicon.ico', 11),
  ('UI 组件 / 设计系统', 'Vue Amazing UI', 'https://themusecatcher.github.io/', 'Vue Amazing UI 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://themusecatcher.github.io/favicon.ico', 12),
  ('UI 组件 / 设计系统', 'Vue3 Context Menu', 'https://docs.imengyu.top/', 'Vue3 Context Menu 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://docs.imengyu.top/vite.svg', 13),
  ('UI 组件 / 设计系统', 'Vue SlickSort', 'https://vue-slicksort.netlify.app/', 'Vue SlickSort 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://vue-slicksort.netlify.app/favicon-32x32.png', 14),
  ('UI 组件 / 设计系统', 'Sweezy Cursors', 'https://sweezy-cursors.com/', 'Sweezy Cursors 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://sweezy-cursors.com/wp-content/uploads/2021/05/cropped-sweezy-icon-512-3-32x32.png', 15),
  ('UI 组件 / 设计系统', 'Algolia 搜索', 'https://www.algolia.com/', 'Algolia 搜索 属于「UI 组件 / 设计系统」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://www.algolia.com/files/live/sites/algolia-assets/files/icons/algolia-logo-for-favicon.svg', 16),
  ('模板 / 市场', 'HTMLRev', 'https://htmlrev.com/', 'HTMLRev 属于「模板 / 市场」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://htmlrev.com/favicon.ico', 0),
  ('模板 / 市场', 'ThemeForest', 'https://themeforest.net/', 'ThemeForest 属于「模板 / 市场」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://assets.market-storefront.envato-static.com/storefront/assets/favicons/favicon-683776860a73328fbfb90221f38228ae31fd55217f17b0fdba2daa1727c47dbd.ico', 1),
  ('模板 / 市场', 'StaticHunt', 'https://statichunt.com/', 'StaticHunt 属于「模板 / 市场」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://statichunt.com/images/favicon.png', 2),
  ('模板 / 市场', 'Built at Lightspeed', 'https://www.builtatlightspeed.com/', 'Built at Lightspeed 属于「模板 / 市场」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://www.builtatlightspeed.com/favicon.ico', 3),
  ('模板 / 市场', 'Jamstack Generators', 'https://jamstack.org/', 'Jamstack Generators 属于「模板 / 市场」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://jamstack.org/img/favicons/apple-touch-icon.png', 4),
  ('模板 / 市场', 'Front Resources', 'https://frontresources.dev/', 'Front Resources 属于「模板 / 市场」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://frontresources.dev/favicon.ico', 5),
  ('模板 / 市场', 'FE-Nav', 'https://fe-nav.netlify.app/', 'FE-Nav 属于「模板 / 市场」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://fe-nav.netlify.app/favicon.ico', 6),
  ('模板 / 市场', 'Free Logo Design', 'https://app.freelogodesign.org/', 'Free Logo Design 属于「模板 / 市场」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://app.freelogodesign.org/favicon.ico', 7),
  ('模板 / 市场', 'Pling', 'https://www.pling.com/', 'Pling 属于「模板 / 市场」，适合查找图标、UI 组件、模板、Logo 和设计灵感。', 'https://www.opendesktop.org/favicon_opendesktop.ico', 8),
  ('VitePress 生态', 'VitePress 官方', 'https://vitepress.dev/zh', 'VitePress 官方 属于「VitePress 生态」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://vitepress.dev/vitepress-logo-mini.svg', 0),
  ('VitePress 生态', 'VitePress Catppuccin', 'https://vitepress.catppuccin.com/', 'VitePress Catppuccin 属于「VitePress 生态」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://raw.githubusercontent.com/catppuccin/catppuccin/refs/heads/main/assets/logos/exports/1544x1544_circle.png', 1),
  ('VitePress 生态', 'VitePress Yiov', 'https://vitepress.yiov.top/', 'VitePress Yiov 属于「VitePress 生态」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://vitepress.yiov.top/logo.png', 2),
  ('VitePress 生态', 'Sugarat Theme', 'https://theme.sugarat.top/', 'Sugarat Theme 属于「VitePress 生态」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://theme.sugarat.top/favicon.ico', 3),
  ('VitePress 生态', 'Hacxy Theme', 'https://theme.hacxy.cn/', 'Hacxy Theme 属于「VitePress 生态」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://theme.hacxy.cn/favicon.ico', 4),
  ('VitePress 生态', 'Best VitePress Themes', 'https://www.bestvuepressthemes.com/', 'Best VitePress Themes 属于「VitePress 生态」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://www.bestvuepressthemes.com/images/favicon/favicon-16x16.png', 5),
  ('VitePress 生态', 'Xugaoyi', 'https://doc.xugaoyi.com/', 'Xugaoyi 属于「VitePress 生态」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://doc.xugaoyi.com/img/favicon.ico', 6),
  ('VitePress 生态', 'Yuy1n', 'https://vp.yuy1n.io/', 'Yuy1n 属于「VitePress 生态」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://vp.yuy1n.io/logo.svg', 7),
  ('VitePress 生态', 'VitePress Timeline 插件', 'https://www.npmjs.com/', 'VitePress Timeline 插件 属于「VitePress 生态」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://www.npmjs.com/favicon.ico', 8),
  ('VitePress 生态', 'Nolebase 集成', 'https://nolebase-integrations.ayaka.io/', 'Nolebase 集成 属于「VitePress 生态」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://nolebase-integrations.ayaka.io/favicon.ico', 9),
  ('VitePress 生态', 'Vite 插件集合', 'https://fengxinming.github.io/', 'Vite 插件集合 属于「VitePress 生态」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://fengxinming.github.io/favicon.ico', 10),
  ('静态站点框架', 'RsPress', 'https://rspress.rs/zh', 'RsPress 属于「静态站点框架」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://assets.rspack.rs/rspress/rspress-logo.svg', 0),
  ('静态站点框架', 'VuePress Theme Reco', 'https://theme-reco.vuejs.press/', 'VuePress Theme Reco 属于「静态站点框架」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://theme-reco.vuejs.press/favicon.ico', 1),
  ('静态站点框架', 'Lumen', 'https://lumen.theojs.cn/', 'Lumen 属于「静态站点框架」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://lumen.theojs.cn/favicon-96x96.png', 2),
  ('静态站点框架', 'Hexo Theme Async', 'https://hexo-theme-async.imalun.com/', 'Hexo Theme Async 属于「静态站点框架」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://hexo-theme-async.imalun.com/logo@64x64.png', 3),
  ('静态站点框架', 'Solitude (Hexo)', 'https://solitude.js.org/cn', 'Solitude (Hexo) 属于「静态站点框架」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://solitude.js.org/favicon.ico', 4),
  ('静态站点框架', 'Anheyu', 'https://docs.anheyu.com/', 'Anheyu 属于「静态站点框架」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://docs.anheyu.com/logo.png', 5),
  ('静态站点框架', 'Pages CMS', 'https://pagescms.org/', 'Pages CMS 属于「静态站点框架」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://pagescms.org/assets/favicon.svg', 6),
  ('文档 / 搜索', 'Orama 搜索', 'https://docs.orama.com/', 'Orama 搜索 属于「文档 / 搜索」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://docs.orama.com/icon.png?c45fa04cd8486eae', 0),
  ('评论系统', 'Waline', 'https://waline.js.org/', 'Waline 属于「评论系统」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://waline.js.org/favicon.ico', 0),
  ('评论系统', 'Twikoo', 'https://twikoo.js.org/', 'Twikoo 属于「评论系统」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://twikoo.js.org/twikoo-logo-mini.png', 1),
  ('评论系统', 'Valine', 'https://valine.js.org/', 'Valine 属于「评论系统」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://valine.js.org/images/icons/apple-touch-icon-152x152.png', 2),
  ('评论系统', 'Gitalk', 'https://gitalk.github.io/', 'Gitalk 属于「评论系统」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://gitalk.github.io/favicon.ico', 3),
  ('评论系统', 'Artalk', 'https://artalk.js.org/', 'Artalk 属于「评论系统」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://artalk.js.org/favicon.png', 4),
  ('评论系统', 'Vssue', 'https://vssue.js.org/', 'Vssue 属于「评论系统」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://vssue.js.org/favicon.ico', 5),
  ('评论系统', 'BSR', 'https://bsr.xinrea.cn/', 'BSR 属于「评论系统」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://bsr.xinrea.cn/favicon.ico', 6),
  ('前端工具', 'React Pick Color', 'https://github.com/', 'React Pick Color 属于「前端工具」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://github.com/fluidicon.png', 0),
  ('前端工具', 'Capsule Render', 'https://capsule-render.vercel.app/', 'Capsule Render 属于「前端工具」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://capsule-render.vercel.app/favicon.ico', 1),
  ('前端工具', 'Readme Typing SVG', 'https://readme-typing-svg.demolab.com/', 'Readme Typing SVG 属于「前端工具」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://readme-typing-svg.demolab.com/demo/favicon.png', 2),
  ('前端工具', 'Vue3 资源', 'https://hu-snail.github.io/', 'Vue3 资源 属于「前端工具」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://hu-snail.github.io/favicon.ico', 3),
  ('前端工具', 'Tauri', 'https://tauri.app/zh-cn', 'Tauri 属于「前端工具」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://tauri.app/favicon.svg', 4),
  ('前端工具', 'Hanochma', 'https://hanochma.github.io/', 'Hanochma 属于「前端工具」，适合查阅前端框架、文档站、搜索、评论系统和开发工具。', 'https://hanochma.github.io/logo.png', 5),
  ('PDF / 文档', 'iLovePDF', 'https://www.ilovepdf.com/zh-cn', 'iLovePDF 属于「PDF / 文档」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://www.ilovepdf.com/img/app-icon.png', 0),
  ('PDF / 文档', 'PDF Translator', 'https://pdftranslator.org/zh', 'PDF Translator 属于「PDF / 文档」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://pdftranslator.org/favicon.ico', 1),
  ('PDF / 文档', 'Open File Viewer', 'https://open-file-viewer-workspace.void.app/', 'Open File Viewer 属于「PDF / 文档」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://open-file-viewer-workspace.void.app/favicon.svg', 2),
  ('生成器', 'EPC QR Code 生成器', 'https://www.qr-code-generator.com/', 'EPC QR Code 生成器 属于「生成器」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://media.qr-code-generator.com/wp-content/uploads/2026/04/20174334/favicon-qrcg-150x150.png', 0),
  ('生成器', 'Text to Handwriting', 'https://text-to-handwriting.org/zh', 'Text to Handwriting 属于「生成器」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://text-to-handwriting.org/favicon.ico', 1),
  ('生成器', 'Handwrite', 'https://handwrite.sixiangjia.de/', 'Handwrite 属于「生成器」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://handwrite.sixiangjia.de/favicon.ico', 2),
  ('生成器', 'CV Template', 'https://cv-template.online/', 'CV Template 属于「生成器」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://cv-template.online/favicon.ico', 3),
  ('生成器', 'Address Generator', 'https://addressgen.top/zh', 'Address Generator 属于「生成器」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://addressgen.top/favicon-16x16.png', 4),
  ('检测 / 分析', 'Whoer - IP检测', 'https://whoer.net/zh', 'Whoer - IP检测 属于「检测 / 分析」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://whoer.net/favicon.ico', 0),
  ('检测 / 分析', 'Scamalytics - 欺诈IP检测', 'https://scamalytics.com/', 'Scamalytics - 欺诈IP检测 属于「检测 / 分析」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://scamalytics.com/favicon.ico', 1),
  ('检测 / 分析', 'VerifTools', 'https://veriftools.net/', 'VerifTools 属于「检测 / 分析」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://veriftools.net/favicon.ico', 2),
  ('检测 / 分析', 'ICP 备案查询', 'https://icp.redcha.cn/', 'ICP 备案查询 属于「检测 / 分析」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://icp.redcha.cn/favicon.ico', 3),
  ('检测 / 分析', 'ICP Moe', 'https://icp.gov.moe/', 'ICP Moe 属于「检测 / 分析」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://icp.gov.moe/images/03.svg', 4),
  ('检测 / 分析', 'ICP Hentioe', 'https://icp.hentioe.dev/', 'ICP Hentioe 属于「检测 / 分析」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://icp.hentioe.dev/favicon-96x96.png', 5),
  ('开发工具', 'TablePlus', 'https://tableplus.com/', 'TablePlus 属于「开发工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://tableplus.com/resources/favicons/apple-icon-57x57.png', 0),
  ('开发工具', 'MarkText', 'https://marktext.me/', 'MarkText 属于「开发工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://marktext.me/favicon.png', 1),
  ('开发工具', 'OnetCLI', 'https://feigecode.github.io/', 'OnetCLI 属于「开发工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://feigecode.github.io/favicon.ico', 2),
  ('开发工具', 'MassGrave - 激活工具', 'https://massgrave.dev/', 'MassGrave - 激活工具 属于「开发工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://massgrave.dev/img/favicon.ico', 3),
  ('设计工具', 'PSD Stencil', 'https://www.psdstencil.cc/', 'PSD Stencil 属于「设计工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://www.psdstencil.cc/wp-content/uploads/2024/05/%E5%9B%BE%E7%89%87_20240514223841-removebg-preview.png', 0),
  ('其他工具', 'Azhu', 'https://azhu.site/', 'Azhu 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://azhu.site/assets/img/favicon.png', 0),
  ('其他工具', 'Rue - 欧洲新银行分析', 'https://rue.ee/cn', 'Rue - 欧洲新银行分析 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://rue.ee/wp-content/uploads/2022/04/rue-logo4Asset-4.svg', 1),
  ('其他工具', '猫啃', 'https://www.maoken.com/', '猫啃 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://www.maoken.com/favicon.ico', 2),
  ('其他工具', 'Saduck', 'https://saduck.top/', 'Saduck 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://saduck.top/favicon64.ico', 3),
  ('其他工具', 'Lizhi Shop', 'https://lizhi.shop/', 'Lizhi Shop 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://lizhi.shop/favicons/favicon-96x96.png', 4),
  ('其他工具', 'Apsgo', 'https://apsgo.com/', 'Apsgo 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://apsgo.com/favicon.ico', 5),
  ('其他工具', 'AI 比价', 'https://aibijia.org/', 'AI 比价 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://aibijia.org/logos/logo.png', 6),
  ('其他工具', 'MR41', 'https://www.mr41.com/', 'MR41 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://www.mr41.com/wp-content/uploads/2023/06/a7q95-h7yhp-001.ico', 7),
  ('其他工具', 'MoneyZine', 'https://moneyzine.com/', 'MoneyZine 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://moneyzine.com/favicon.ico', 8),
  ('其他工具', 'Teddysun', 'https://teddysun.com/', 'Teddysun 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://teddysun.com/favicon.ico', 9),
  ('其他工具', 'NBW Nav', 'https://nav.nbw.one/', 'NBW Nav 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://nav.nbw.one/wp-content/themes/WebStack-1.2024/images/favicon.png', 10),
  ('其他工具', 'NBW', 'https://www.nbw.one/', 'NBW 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://www.nbw.one/wp-content/uploads/2025/04/cropped-logo-32x32.png', 11),
  ('其他工具', 'OpenPGP', 'https://www.openpgp.org/', 'OpenPGP 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://www.openpgp.org/images/apple-touch-icon.png', 12),
  ('其他工具', 'Regtons', 'https://regtons.com/en', 'Regtons 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://regtons.com/img/favicon.ico', 13),
  ('其他工具', 'SMR-JS', 'https://www.smr-js.com/', 'SMR-JS 属于「其他工具」，适合处理文档、生成内容、检测分析或日常效率任务。', 'https://zcbk.smr-js.com/wp-content/uploads/2025/05/QQ_1748605267935-removebg-preview.png', 14),
  ('转运与物流', 'TipTrans', 'https://www.tiptrans.com/', 'TipTrans 是转运或物流服务入口，适合管理跨境转运、包裹收发和海外地址。', 'https://www.tiptrans.com/images/favicon.ico', 0),
  ('转运与物流', 'Shipito', 'https://www.shipito.com/zh', 'Shipito 是转运或物流服务入口，适合管理跨境转运、包裹收发和海外地址。', 'https://www.shipito.com/favicon.ico', 1),
  ('转运与物流', 'Tenso (日本转运)', 'https://www.tenso.com/', 'Tenso (日本转运) 是转运或物流服务入口，适合管理跨境转运、包裹收发和海外地址。', 'https://www.tenso.com/favicon.ico', 2),
  ('转运与物流', 'JChere (日本转运)', 'https://www.jchere.com/', 'JChere (日本转运) 是转运或物流服务入口，适合管理跨境转运、包裹收发和海外地址。', 'https://www.jchere.com/favicon.ico', 3),
  ('转运与物流', 'Anytime Mailbox', 'https://www.anytimemailbox.com/', 'Anytime Mailbox 是转运或物流服务入口，适合管理跨境转运、包裹收发和海外地址。', 'https://www.anytimemailbox.com/wp-content/uploads/2024/08/cropped-ATMB-Favicon-32x32.png', 4),
  ('转运与物流', 'VeriDocs', 'https://doc.veridocs.cc/', 'VeriDocs 是转运或物流服务入口，适合管理跨境转运、包裹收发和海外地址。', 'http://doc.veridocs.cc/wp-content/uploads/2023/02/1677321226-cac92ae1d98ef2a.png', 5),
  ('转运与物流', 'iPostalMail', 'https://client.ipostalmail.net/', 'iPostalMail 是转运或物流服务入口，适合管理跨境转运、包裹收发和海外地址。', 'https://client.ipostalmail.net/favicon.ico', 6),
  ('转运与物流', 'Skypax', 'https://www.skypax.com/', 'Skypax 是转运或物流服务入口，适合管理跨境转运、包裹收发和海外地址。', 'https://www.skypax.com/assets/images/favicon.jpg', 7),
  ('转运与物流', 'Royal Mail (英国)', 'https://www.royalmail.com/', 'Royal Mail (英国) 是转运或物流服务入口，适合管理跨境转运、包裹收发和海外地址。', 'https://www.royalmail.com/themes/custom/rmlcwr/favicon.ico', 8),
  ('Mac 软件下载', 'MacWK', 'https://macwk.cn/', 'MacWK 属于「Mac 软件下载」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://macwk.cn/wp-content/uploads/2023/07/macwkico.png', 0),
  ('Mac 软件下载', 'Sysin', 'https://sysin.org/', 'Sysin 属于「Mac 软件下载」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://sysin.org/img/favicon.png', 1),
  ('Mac 软件下载', 'MacBL', 'https://www.macbl.com/', 'MacBL 属于「Mac 软件下载」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://macbl01.skqandroid.com/images/favicon.ico', 2),
  ('Mac 软件下载', 'AppStorrent', 'https://appstorrent.ru/', 'AppStorrent 属于「Mac 软件下载」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://appstorrent.ru/favicon.ico', 3),
  ('Mac 软件下载', 'AppStorrent Org', 'https://appstorrent.org/', 'AppStorrent Org 属于「Mac 软件下载」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://appstorrent.org/favicon.ico', 4),
  ('Mac 软件下载', 'MacDo', 'https://www.macdo.cn/', 'MacDo 属于「Mac 软件下载」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://www.macdo.cn/favicon.ico', 5),
  ('Mac 软件下载', 'Macked', 'https://macked.app/', 'Macked 属于「Mac 软件下载」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://macked.app/wp-content/uploads/favicon.png', 6),
  ('Mac 软件下载', 'MacUpdate', 'https://www.macupdate.com/', 'MacUpdate 属于「Mac 软件下载」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://static.macupdate.com/site/img/common/favicon.png', 7),
  ('Mac 软件下载', 'Waerfa', 'https://www.waerfa.com/', 'Waerfa 属于「Mac 软件下载」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://www.waerfa.com/favicon.ico', 8),
  ('Mac 软件下载', 'IndieGoodies', 'https://indiegoodies.com/', 'IndieGoodies 属于「Mac 软件下载」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://indiegoodies.com/rocket.svg', 9),
  ('Mac 资源', '少数派', 'https://sspai.com/', '少数派 属于「Mac 资源」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://cdn-static.sspai.com/favicon/sspai.ico', 0),
  ('Windows / Linux', 'YYCZXT', 'https://www.yyczxt.com/', 'YYCZXT 属于「Windows / Linux」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://www.yyczxt.com/static/img/favicon.svg', 0),
  ('Windows / Linux', 'WinNew', 'https://winnew.cn/', 'WinNew 属于「Windows / Linux」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://winnew.cn/favicon.ico', 1),
  ('Windows / Linux', 'ZhuangIT', 'https://zhuangit.ababtools.com/', 'ZhuangIT 属于「Windows / Linux」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://zhuangit.ababtools.com/favicon.svg', 2),
  ('Windows / Linux', 'DistroWatch', 'https://distrowatch.com/', 'DistroWatch 属于「Windows / Linux」，适合查找 Mac 软件、系统工具、装机资源和应用下载。', 'https://distrowatch.com/favicon.ico', 3),
  ('Android 与 Custom ROM', 'PixelOS', 'https://pixelos.net/', 'PixelOS 是 Android 或 Custom ROM 资源入口，适合查阅 ROM、设备社区和移动系统资料。', 'https://pixelos.net/favicon.ico?favicon.14pzhoo70if9g.ico', 0),
  ('Android 与 Custom ROM', 'crDroid', 'https://crdroid.net/', 'crDroid 是 Android 或 Custom ROM 资源入口，适合查阅 ROM、设备社区和移动系统资料。', 'https://crdroid.net/img/favicon.ico', 1),
  ('Android 与 Custom ROM', 'LineageOS', 'https://wiki.lineageos.org/', 'LineageOS 是 Android 或 Custom ROM 资源入口，适合查阅 ROM、设备社区和移动系统资料。', 'https://wiki.lineageos.org/images/favicons/apple-touch-icon.png', 2),
  ('Android 与 Custom ROM', 'Pixel Experience', 'https://get.pixelexperience.org/', 'Pixel Experience 是 Android 或 Custom ROM 资源入口，适合查阅 ROM、设备社区和移动系统资料。', 'https://get.pixelexperience.org/favicon-32x32.png', 3),
  ('Android 与 Custom ROM', 'LMO Droid', 'https://lmo.framer.website/', 'LMO Droid 是 Android 或 Custom ROM 资源入口，适合查阅 ROM、设备社区和移动系统资料。', 'https://framerusercontent.com/modules/w3IbWpBN9ldxIITH3nUp/WievrbXzHUeI4N2hgRZM/assets/17XIWwhLsjyHpwZXlKpJ54HTNc.png', 4),
  ('Android 与 Custom ROM', 'XDA Custom ROM', 'https://xdaforums.com/', 'XDA Custom ROM 是 Android 或 Custom ROM 资源入口，适合查阅 ROM、设备社区和移动系统资料。', 'https://xdaforums.com/favicon.ico', 5),
  ('Android 与 Custom ROM', 'APK Mirror', 'https://www.apkmirror.com/', 'APK Mirror 是 Android 或 Custom ROM 资源入口，适合查阅 ROM、设备社区和移动系统资料。', 'https://www.apkmirror.com/wp-content/themes/APKMirror/images/favicon.ico?v=2', 6),
  ('导航站与资源目录', 'HelloGitHub', 'https://hellogithub.com/', 'HelloGitHub 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://hellogithub.com/favicon/favicon.svg', 0),
  ('导航站与资源目录', 'FMHY - 免费资源大全', 'https://fmhy.net/', 'FMHY - 免费资源大全 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://fmhy.net/test.png', 1),
  ('导航站与资源目录', 'QixinPro 导航', 'https://nav.qixinpro.com/', 'QixinPro 导航 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://nav.qixinpro.com/wp-content/uploads/2022/01/cropped-%E5%A5%87.png', 2),
  ('导航站与资源目录', 'DBZDK', 'https://dbzdk.com/', 'DBZDK 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://dbzdk.com/static/images/favicon/favicon-16x16.png', 3),
  ('导航站与资源目录', 'GoPojie', 'https://www.gopojie.com/', 'GoPojie 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://gopojie.com/favicon.ico', 4),
  ('导航站与资源目录', 'OSS Nav', 'https://www.ossnav.com/', 'OSS Nav 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://www.ossnav.com/favicon.ico', 5),
  ('导航站与资源目录', 'Redman3721', 'https://www.redman3721.com/', 'Redman3721 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://www.redman3721.com/wp-content/uploads/2025/04/1744615791-redman_favicon.png', 6),
  ('导航站与资源目录', 'CKey', 'https://ckey.run/', 'CKey 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://ckey.run/favicon.ico', 7),
  ('导航站与资源目录', 'IFC Tribe', 'https://ifctribe.com/', 'IFC Tribe 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://ifctribe.com/wp-content/uploads/2024/09/favicon-32x32-1.png', 8),
  ('导航站与资源目录', 'Imsyy Blog', 'https://blog.imsyy.top/', 'Imsyy Blog 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://blog.imsyy.top/favicon.ico', 9),
  ('导航站与资源目录', 'Butterfly', 'https://butterfly.js.org/', 'Butterfly 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://butterfly.js.org/img/favicon.ico', 10),
  ('导航站与资源目录', 'Miao3', 'https://www.miao3.cn/', 'Miao3 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://oss.miao3.cn/assets/img/favicon.ico', 11),
  ('导航站与资源目录', 'Cuckooing', 'https://cs.cuckooing.cn/', 'Cuckooing 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://cs.cuckooing.cn/favicon.ico', 12),
  ('导航站与资源目录', 'NavNav', 'https://navnav.co/', 'NavNav 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://navnav.co/favicon.ico', 13),
  ('导航站与资源目录', 'Weiyangx', 'https://www.weiyangx.com/', 'Weiyangx 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://www.weiyangx.com/favicon.ico', 14),
  ('导航站与资源目录', 'Gachago', 'https://www.gachago.net/zh-cn', 'Gachago 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://www.gachago.net/favicon.ico?favicon.037zapx3vjmu1.ico', 15),
  ('导航站与资源目录', 'BiliUniverse', 'https://biliuniverse.io/', 'BiliUniverse 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://biliuniverse.io/favicon.ico', 16),
  ('导航站与资源目录', 'Milkup', 'https://milkup.dev/', 'Milkup 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://milkup.dev/logo.svg', 17),
  ('导航站与资源目录', 'Yiguess', 'https://yiguess.top/', 'Yiguess 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'http://yiguess.top/wp-content/uploads/2025/04/4a47a0db6e20250422195940.png', 18),
  ('导航站与资源目录', 'CrossDesk', 'https://www.crossdesk.cn/', 'CrossDesk 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://www.crossdesk.cn/favicon.ico', 19),
  ('导航站与资源目录', 'XSZN', 'https://xszn.org/', 'XSZN 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://xszn.org/favicon.ico', 20),
  ('导航站与资源目录', 'Ahu Blog', 'https://blog.ahu.moe/', 'Ahu Blog 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://static.ahu.moe/static/header.ico', 21),
  ('导航站与资源目录', 'AppMiu', 'https://www.appmiu.com/', 'AppMiu 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://pics.amiao.app/2023/03/26221931/20230318045039758-32x32.png', 22),
  ('导航站与资源目录', 'Hats Land', 'https://www.hats-land.com/', 'Hats Land 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://random-cat-assets-r2.hats-land.com/api/v1/images?format=png&amp;b=c2hvcnRjdXQgaWNvbg', 23),
  ('导航站与资源目录', 'Kaolarj', 'https://www.kaolarj.com/', 'Kaolarj 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://www.kaolarj.com/favicon.ico', 24),
  ('导航站与资源目录', 'Linux.do', 'https://linux.do/', 'Linux.do 是导航或资源目录入口，适合收藏综合站点、教程、社区和软件资源。', 'https://linux.do/favicon.ico', 25),
  ('游戏', 'Buff - CS/Dota饰品', 'https://buff.163.com/', 'Buff - CS/Dota饰品 是游戏相关入口，适合查找游戏平台、市场、资源或娱乐内容。', 'https://buff.163.com/favicon.ico', 0),
  ('游戏', 'Youpin898 游戏交易', 'https://www.youpin898.com/', 'Youpin898 游戏交易 是游戏相关入口，适合查找游戏平台、市场、资源或娱乐内容。', 'https://www.youpin898.com/favicon.ico', 1),
  ('游戏', 'Steam 市场', 'https://steamcommunity.com/', 'Steam 市场 是游戏相关入口，适合查找游戏平台、市场、资源或娱乐内容。', 'https://steamcommunity.com/favicon.ico', 2),
  ('游戏', 'Best Party Games', 'https://www.bestpartygames.net/zh', 'Best Party Games 是游戏相关入口，适合查找游戏平台、市场、资源或娱乐内容。', 'https://www.bestpartygames.net/image/favicon.png', 3),
  ('游戏', 'FitGirl Repacks', 'https://fitgirl-repacks.site/', 'FitGirl Repacks 是游戏相关入口，适合查找游戏平台、市场、资源或娱乐内容。', 'https://fitgirl-repacks.site/wp-content/uploads/2016/08/cropped-icon-32x32.jpg', 4),
  ('游戏', 'Eneba - 游戏礼品卡', 'https://www.eneba.com/zh', 'Eneba - 游戏礼品卡 是游戏相关入口，适合查找游戏平台、市场、资源或娱乐内容。', 'https://static.eneba.games/favicon.ico', 5),
  ('购物', 'Shop.app', 'https://shop.app/', 'Shop.app 是购物入口，适合购买数字商品、软件、礼品卡或数码周边。', 'https://shop.app/favicon.ico', 0),
  ('购物', 'Amazon', 'https://www.amazon.com/', 'Amazon 是购物入口，适合购买数字商品、软件、礼品卡或数码周边。', 'https://www.amazon.com/favicon.ico', 1),
  ('购物', 'Fiverr', 'https://www.fiverr.com/', 'Fiverr 是购物入口，适合购买数字商品、软件、礼品卡或数码周边。', 'https://www.fiverr.com/favicon.ico', 2)
)
INSERT INTO navigation_items (group_id, name, url, note, icon_url, sort_order)
SELECT navigation_groups.id, desired_items.name, desired_items.url, desired_items.note, desired_items.icon_url, desired_items.sort_order
FROM desired_items
INNER JOIN navigation_groups ON lower(navigation_groups.name) = lower(desired_items.group_name)
WHERE NOT EXISTS (
  SELECT 1
  FROM navigation_items existing_items
  WHERE existing_items.url = desired_items.url
);
