SET TIME ZONE 'Asia/Shanghai';

-- Update seeded navigation website notes from bookmarks_html.html.
-- Matching uses the current seeded navigation item URL as the update target.
WITH desired_notes(url, note) AS (
  VALUES
  ('https://www.nab.com.au/', '澳大利亚国民银行，提供基础日常账户，无月费，支持澳元存取款及网银服务。'),
  ('https://www.1822direkt.de/', '德国直销银行，法兰克福储蓄银行旗下品牌，提供免费活期账户、储蓄及证券服务。'),
  ('https://www.umweltbank.de/', '德国绿色银行，专注可持续投资与环保项目融资，提供绿色储蓄和贷款产品。'),
  ('https://www.bpi.com.ph/', '菲律宾岛屿银行，菲律宾历史最悠久的银行之一，提供个人、企业及数字银行服务。'),
  ('https://www.bbva.de/', '西班牙对外银行德国分支，提供免费数字账户，支持欧元区转账及储蓄功能。'),
  ('https://www.frankfurter-sparkasse.de/', '法兰克福储蓄银行，德国区域性储蓄银行，提供全面的个人和企业金融服务。'),
  ('https://www.tomorrow.one/en-EU', '德国可持续发展数字银行，每次消费都会将部分资金用于气候保护和环保项目。'),
  ('https://www.expat.hsbc.com/', '汇丰银行专为海外侨民设计的离岸账户服务，支持多币种持有和国际转账。'),
  ('https://neo-bank.com/', '加拿大数字银行，提供高息储蓄账户、现金返还信用卡及无手续费日常账户。'),
  ('https://nickel.eu/fr', '法国大众化数字账户，可在烟草店开户，无需信用审核，适合信用记录不佳人群。'),
  ('https://www.yuh.com/en', '瑞士数字金融应用，由 Swissquote 和 PostFinance 联合推出，支持银行、储蓄和投资。'),
  ('https://tonikbank.com/', '菲律宾首家纯数字银行，提供高息存款、贷款及即时转账，完全无实体网点。'),
  ('https://www.uno.bank/', '菲律宾数字银行，提供简洁的储蓄账户和贷款服务，主打低门槛快速开户体验。'),
  ('https://clear.bank/', '英国清算银行基础设施提供商，主要为金融机构和金融科技公司提供银行清算服务。'),
  ('https://satchel.eu/', '欧洲电子货币机构，提供 IBAN 账户、SEPA 转账及多币种支付服务，适合企业使用。'),
  ('https://kontist.com/', '德国面向自由职业者的数字银行，内置税务预估功能，自动分离税款与可支配收入。'),
  ('https://grey.co/', '面向非洲用户的跨境金融平台，提供美元、英镑、欧元虚拟账户，方便接收海外收入。'),
  ('https://aspireapp.com/', '东南亚企业数字金融平台，提供商业账户、企业卡、支出管理及跨境收付款服务。'),
  ('https://www.payset.io/', '英国电子货币机构，提供多币种 IBAN 账户和 SWIFT/SEPA 国际支付服务。'),
  ('https://www.contomobile.com/', '欧洲数字账户服务商，提供即时 IBAN、SEPA 转账及虚拟/实体 Visa 卡。'),
  ('https://bilderlings.com/', '拉脱维亚持牌支付机构，提供欧元 IBAN 账户、SEPA/SWIFT 转账及货币兑换服务。'),
  ('https://www.olky.eu/en', '卢森堡持牌支付机构，提供个人和企业欧元账户，支持 SEPA 即时转账。'),
  ('https://www.moneybase.com/', '马耳他数字金融平台，提供个人和企业 IBAN 账户、储蓄及加密资产管理服务。'),
  ('https://finci.com/', '格鲁吉亚数字银行，提供多币种账户、国际转账及企业支付解决方案。'),
  ('https://pinkwallet.com/', '电子钱包平台，提供账户充值、P2P 转账和在线支付功能，界面简洁易用。'),
  ('https://www.paytrip.fr/', '法国旅行专用预付卡账户，免外币手续费，适合频繁出行的用户。'),
  ('https://www.mizen.eu/', '比利时电子货币账户，提供灵活套餐的 IBAN 账户和 Mastercard 卡。'),
  ('https://www.musc-pay.com/', '欧洲支付账户，提供 IBAN 账户和 Mastercard 预付卡，支持多币种日常消费。'),
  ('https://noelse.com/', '比利时数字银行账户，提供即时 IBAN、Visa 卡及简洁的支出追踪功能。'),
  ('https://www.bebunk.com/', '欧洲数字金融账户平台，提供 IBAN 账户、多币种支付及虚拟卡服务。'),
  ('https://www.vertofx.com/', '面向企业的多币种外汇平台，支持 200+ 种货币兑换，提供实时汇率和批量付款。'),
  ('https://wallet.spush.co.uk/', '英国数字钱包，提供即时转账和在线支付功能，主打简洁快速的用户体验。'),
  ('https://wireaccount.com/', '欧洲在线账户服务，提供 IBAN 账户和 SWIFT 国际电汇，适合个人和中小企业。'),
  ('https://www.moneygate.com/', '欧洲支付平台，提供企业 IBAN 账户、批量付款及跨境收付款解决方案。'),
  ('https://olamit.com/', '以色列支付平台，提供数字钱包和在线支付服务，支持多种货币和支付渠道。'),
  ('https://cactuspay.com/', '数字支付账户，提供 IBAN 及多币种管理功能，面向个人和小型企业用户。'),
  ('https://www.cfps.co/', '跨境金融支付服务提供商，为企业提供国际收付款和多币种结算解决方案。'),
  ('https://banxe.com/', '英国金融科技平台，融合传统银行账户与加密货币功能，支持法币和数字资产管理。'),
  ('https://novapay.com/en', '乌克兰数字支付平台，与 Nova Poshta 快递深度整合，提供电子钱包和网络支付服务。'),
  ('https://www.kixy.com/', '英国电子货币账户，提供多币种持有、汇率兑换及 Visa 借记卡，主打低汇兑费用。'),
  ('https://monitox.com/', '欧洲数字支付账户，提供 IBAN 账户和 Visa 预付卡，支持多币种管理和国际转账。'),
  ('https://credits.com/en', '区块链支付平台，基于自研高性能公链，提供快速低成本的数字资产转账服务。'),
  ('https://payz.com/', '原 ecoPayz，国际电子钱包，支持多币种账户和全球商户支付，在博彩领域使用较多。'),
  ('https://finsei.com/', '欧洲持牌支付机构，提供个人和企业电子账户、国际支付及货币兑换服务。'),
  ('https://verifo.com/', '立陶宛持牌支付机构，提供欧元 IBAN 账户、SEPA 转账及货币兑换服务。'),
  ('https://www.bnkpro.com/', '面向企业的欧洲数字银行账户，提供多币种 IBAN、国际支付及合规 KYB 验证服务。'),
  ('https://www.yonder.com/', '英国旅行奖励信用卡，无外币手续费，消费积累积分可兑换餐厅和旅行体验。'),
  ('https://getmeru.com/', '面向印度用户的全球金融账户，提供美元账户及跨境收款服务，适合远程工作者。'),
  ('https://www.beansapp.com/', '数字内容和应用推荐平台，提供各类 App 和数字产品的发现和下载服务。'),
  ('https://moneyjar.world/', '数字储蓄账户平台，帮助用户设立多个储蓄目标罐，养成分类储蓄习惯。'),
  ('https://moneco.app/', '面向非洲侨民的欧洲数字银行，提供欧元账户及低费率向非洲国家汇款服务。'),
  ('https://www.spendo.com/', '欧洲数字支出管理平台，提供企业预付卡和费用报销自动化工具。'),
  ('https://myguava.com/', '英国数字商业账户，专为中小企业设计，提供多币种账户和支出管理功能。'),
  ('https://www.plutus.it/', '英国 DeFi 借记卡平台，消费可获得加密货币返现，支持 Visa 消费和 DeFi 质押奖励。'),
  ('https://keytom.com/', '软件激活码和数字产品购买平台，提供 Windows、Office 等软件的正版授权密钥。'),
  ('https://cer.live/', '实时汇率和货币兑换工具，提供主要货币对的实时汇率查询和历史走势图表。'),
  ('https://bumba.global/en', '全球数字支付平台，提供多币种账户和国际转账服务，面向跨境商务人士。'),
  ('https://www.currenc.com.au/', '澳大利亚跨境支付平台，专注亚太地区汇款，提供竞争性汇率和多种收款方式。'),
  ('https://hrbank.com/', '离岸银行服务平台，为个人和企业提供境外账户开设及跨境金融解决方案。'),
  ('https://aminagroup.com/', '瑞士持牌加密银行，提供传统银行服务与数字资产托管、交易的一体化解决方案。'),
  ('https://www.kuajinzhifu.com/', '面向跨境电商卖家的收款和结汇平台，支持亚马逊、eBay 等主流平台资金提现。'),
  ('https://www.moneycorp.com/en', '英国老牌外汇及国际汇款机构，提供竞争性汇率和企业外汇风险管理服务。'),
  ('https://www.moneycorpbank.com/', 'Moneycorp 旗下持牌银行，提供外汇账户、定期存款及国际汇款银行级服务。'),
  ('https://www.ludpay.com/', '国际支付平台，提供多币种账户和低成本跨境汇款服务，面向个人和企业。'),
  ('https://www.captrexglobal.com/', '全球支付和收款解决方案提供商，为企业提供多币种账户和国际贸易支付服务。'),
  ('https://finseta.com/', '英国跨境支付机构，专注企业级多币种收付款和国际贸易结算解决方案。'),
  ('https://weststeincard.com/', '欧洲预付 Visa 卡及电子账户，支持 SEPA 转账，无需信用记录即可申请。'),
  ('https://my.sogexia.com/', '法国电子货币账户，提供法语服务，支持 IBAN、SEPA 转账及 Mastercard 借记卡。'),
  ('https://client.quantpayment.com/', '欧洲支付机构，提供个人和企业 IBAN 账户及国际电汇服务，合规监管严格。'),
  ('https://xportal.com/', 'MultiversX 生态超级应用，融合数字钱包、NFT、DeFi 和 Web3 身份于一体。'),
  ('https://altery.com/', '欧洲数字账户平台，提供多币种 IBAN、即时 SEPA 转账及虚拟 Visa 卡服务。'),
  ('https://pay.alphapay.lt/', '立陶宛支付平台，提供欧元账户和 SEPA 转账服务，面向欧洲个人和企业用户。'),
  ('https://www.currencysolutions.com/', '英国外汇经纪商，提供个人和企业国际汇款服务，汇率优于银行标准汇率。'),
  ('https://www.fairfx.com/', '英国外汇服务商，提供旅行货币卡、网络换汇及企业国际支付，汇率透明无隐藏费用。'),
  ('https://caxton.io/', '英国多币种旅行卡，支持 30+ 种货币锁定汇率，海外消费无手续费。'),
  ('https://quidglobal.com/', '国际支付平台，专注新兴市场跨境汇款，提供实时汇率和低手续费转账服务。'),
  ('https://dashboard.fasterpay.com/', '全球支付解决方案，为游戏、订阅及数字内容商家提供收款和跨境结算服务。'),
  ('https://rutlandfx.com/', '英国精品外汇经纪商，专注为中小企业提供定制化外汇对冲和国际支付服务。'),
  ('https://equalsmoney.com/', '英国企业支出管理平台，提供多币种账户、企业卡及国际付款一体化解决方案。'),
  ('https://online.torfx.com/', '英国知名外汇转账服务，提供专属客户经理和优惠汇率，适合大额国际汇款。'),
  ('https://www.yoursafe.com/en', '欧洲数字账户，提供 IBAN、Mastercard 卡及多币种支付，注重个人数据隐私保护。'),
  ('https://www.binance.com/zh-CN', '全球最大加密货币交易所，提供现货、合约、理财、NFT 等全面服务，交易量全球第一。'),
  ('https://www.okx.com/zh-hans', '全球领先综合加密平台，提供现货、衍生品、Web3 钱包和 DeFi 服务，用户量庞大。'),
  ('https://www.bybit.com/', '全球知名衍生品交易所，以合约交易见长，同时提供现货、理财和 NFT 市场。'),
  ('https://www.bitget.com/zh-CN', '主打跟单交易的综合交易所，提供现货、合约及一键跟单功能，在新兴市场增长迅速。'),
  ('https://www.gate.io/zh', '老牌综合交易所，上币数量众多，支持现货、合约、IEO 和多链钱包服务。'),
  ('https://www.kraken.com/zh-cn', '美国老牌合规交易所，以安全性著称，提供现货、保证金及期货交易，受严格监管。'),
  ('https://www.coinbase.com/', '美国最大合规加密交易所，已在纳斯达克上市，适合新手，监管合规度高。'),
  ('https://www.bitfinex.com/', '香港老牌交易所，以大额交易和保证金借贷著称，流动性深厚，面向专业交易者。'),
  ('https://cex.io/', '英国持牌加密交易所，支持信用卡购币、现货交易和质押服务，合规监管健全。'),
  ('https://whitebit.com/zh-cn', '欧洲领先加密交易所，提供现货、合约、质押及企业级 API 服务，用户增长快速。'),
  ('https://nexo.com/zh', '加密借贷平台，支持以数字资产作为抵押获取法币贷款，同时提供高息存币服务。'),
  ('https://www.bitmart.com/zh-CN', '全球综合交易所，上币种类丰富，提供现货和合约交易，面向全球新兴市场用户。'),
  ('https://www.htx.com/zh-cn', '原火币交易所，老牌综合加密平台，提供现货、合约、理财及区块链生态服务。'),
  ('https://www.xt.com/zh-CN', '全球综合交易所，上币品种极多，提供现货、合约及社交交易功能。'),
  ('https://www.coinw.com/', '老牌综合加密交易所，提供现货、合约、理财及跟单功能，在中文用户群体中有一定知名度。'),
  ('https://www.probit.com/zh-cn', '韩国加密交易所，以频繁上新币和低费率著称，同时提供 IEO 平台和质押服务。'),
  ('https://www.bifinance.com/', '综合加密交易所，提供现货和衍生品交易，着力拓展东南亚新兴市场。'),
  ('https://www.hibt.com/', '新兴加密交易平台，提供现货和合约交易，主打简洁界面和低手续费。'),
  ('https://latoken.com/zh', '专注新资产流动性的交易所，上新项目多，提供现货交易和 IEO 首发平台服务。'),
  ('https://big.one/cn', '综合加密资产交易平台，提供现货交易、理财和节点服务，背靠 EOS 生态。'),
  ('https://www.coinex.com/zh-hans', '专注全球化的综合交易所，上币广泛，提供现货、合约和 AMM 流动性挖矿服务。'),
  ('https://www.bitstamp.net/', '欧洲最古老的比特币交易所之一，以稳健合规著称，主要面向机构和专业投资者。'),
  ('https://www.bitpanda.com/en', '奥地利合规投资平台，支持加密货币、股票、ETF 和贵金属投资，面向欧洲用户。'),
  ('https://www.rain.com/', '中东及北非持牌加密交易所，合规运营，支持当地法币入金，适合该地区用户。'),
  ('https://exmo.com/zh', '东欧和俄语区主流加密交易所，支持卢布、格里夫纳等本地货币，覆盖独联体市场。'),
  ('https://bitvavo.com/en', '荷兰持牌加密交易所，费率低廉，支持欧元直接交易，是荷兰及欧洲用户热门选择。'),
  ('https://blofin.com/', '专注衍生品的加密交易所，提供高流动性合约交易和理财产品，面向专业交易者。'),
  ('https://neverless.com/', '德国新兴数字银行，提供欧元账户和投资功能，面向年轻用户和数字游民。'),
  ('https://app.straitsx.com/', '新加坡持牌支付机构，提供新元稳定币 XSGD 和法币与数字资产的转换服务。'),
  ('https://www.ju.com/zh-CN', '综合数字资产交易平台，提供现货交易、理财和区块链生态服务。'),
  ('https://www.hotcoin.com/', '面向全球华语用户的综合交易所，提供现货、合约和理财服务。'),
  ('https://www.bittap.com/', '新兴加密交易平台，提供数字资产买卖和钱包功能，界面简洁适合入门用户。'),
  ('https://www.bitgp.com/', '加密货币交易平台，提供现货交易和资产管理服务，面向全球用户。'),
  ('https://go.coinmetro.com/', '欧洲持牌加密交易平台，费率透明低廉，提供现货交易、跟单和质押服务。'),
  ('https://app.smartvalor.com/', '瑞士持牌加密交易所，提供合规的数字资产买卖和托管服务，注重监管合规。'),
  ('https://payeer.com/', '俄语区流行的电子支付系统，支持多币种账户、加密货币兑换及国际转账。'),
  ('https://app.airtm.io/', '拉美地区流行的数字美元钱包，通过 P2P 网络帮助用户将当地货币兑换为美元并汇出。'),
  ('https://account.skrill.com/', '欧洲老牌电子钱包，支持多币种账户、国际汇款及在线支付，在博彩和游戏领域广泛使用。'),
  ('https://www.epay.com/', '保加利亚本地电子支付平台，支持水电煤缴费、网络购物及银行转账。'),
  ('https://www.paypal.com/', '全球最大的在线支付平台，支持个人转账、网购付款及跨境收付款，覆盖 200+ 个国家。'),
  ('https://crm.etana.com/', '美国合规金融基础设施平台，为加密货币交易所和金融机构提供法币托管和结算服务。'),
  ('https://codegopay.com/', '在线支付解决方案提供商，支持多种支付方式集成，面向中小型电商和数字服务商家。'),
  ('https://www.tropipay.com/', '面向古巴及拉美用户的跨境支付平台，支持国际汇款和在线购物消费。'),
  ('https://online.neomoon.app/', '新兴数字支付平台，提供电子钱包和跨境转账功能，面向个人和小型企业用户。'),
  ('https://uphold.com/', '美国多资产金融平台，支持法币、加密货币及贵金属的持有和即时兑换。'),
  ('https://qvapay.com/', '古巴数字支付平台，支持多种货币和加密货币，帮助用户进行国际收付款。'),
  ('https://www.ifastgb.com/zh', 'iFAST 英国分支，提供财富管理平台，支持基金、债券投资及英镑账户服务。'),
  ('https://paysend.com/', '全球在线汇款平台，支持向 170+ 个国家转账，费率固定透明，手机操作便捷。'),
  ('https://www.hurupay.com/', '面向非洲的跨境支付平台，提供低成本向非洲国家汇款及本地货币收款服务。'),
  ('https://sendwirepay.com/', '国际汇款平台，提供银行级安全的跨境电汇服务，支持多种货币和收款方式。'),
  ('https://takenos.com/', '阿根廷加密支付平台，帮助用户以稳定币保存资产，规避本地通货膨胀风险。'),
  ('https://volet.com/zh', '欧洲电子钱包平台，支持多币种收付款、SEPA 转账及在线购物，在东欧地区较为流行。'),
  ('https://wallet.moneycollect.com/', '全球支付收款平台，支持加密货币和法币收款，面向跨境电商和数字内容创作者。'),
  ('https://portal.jeton.com/', '英国电子钱包，支持多币种充值、P2P 转账及在线购物支付，在新兴市场覆盖广。'),
  ('https://portal.m-pay.me/', '欧洲电子货币平台，提供个人和企业 IBAN 账户及在线支付服务。'),
  ('https://coinmarketcap.com/zh', '全球最权威的加密货币行情数据平台，提供价格、市值、交易量排名及项目信息。'),
  ('https://esim.holafly.com/cn', '西班牙旅行 eSIM 品牌，提供全球 170+ 个目的地的无限流量套餐，按天计费使用方便。'),
  ('https://www.9esim.com/zh', '全球旅行 eSIM 服务，覆盖多国流量套餐，价格实惠，支持即时激活使用。'),
  ('https://www.estk.me/', '全球 eSIM 平台，提供多国数据套餐，支持一张 eSIM 切换不同国家流量。'),
  ('https://www.switchesim.com/', '多国 eSIM 流量套餐平台，提供灵活的区域套餐选择，适合跨国旅行用户。'),
  ('https://xesim.cc/', '全球旅行 eSIM 服务商，提供多国和地区流量套餐，价格透明即买即用。'),
  ('https://esim.redteago.com/zh-CN', '旅行 eSIM 平台，覆盖亚太、欧洲等多个地区，提供数据套餐和语音服务。'),
  ('https://www.somegadget.shop/en', '科技配件商店与 Topsi 合作推出的旅行 eSIM 套餐，适合购买设备时一并配置流量。'),
  ('https://goesim.hk/', '香港 eSIM 服务商，提供亚洲多国流量套餐，适合出行亚洲地区的旅客。'),
  ('https://docofcard.com/', '实体 SIM 卡购买平台，提供全球多国预付电话卡，可直接邮寄到家。'),
  ('https://esimdb.com/', '全球 eSIM 套餐比价平台，汇聚多家供应商的价格，方便用户选择最优方案。'),
  ('https://tello.com/', '美国 MVNO 运营商，基于 T-Mobile 网络，提供灵活的月租套餐，价格低廉无合约。'),
  ('https://www.sunrise.ch/en', '瑞士第二大电信运营商，提供移动、宽带和电视服务，网络覆盖全面。'),
  ('https://shop.lifecell.ua/en', '乌克兰主要移动运营商之一，提供预付和后付套餐，支持 eSIM 开通。'),
  ('https://meuplanoclaro.com.br/', '巴西 Claro 运营商 eSIM 服务，提供本地和漫游数据套餐，网络覆盖广泛。'),
  ('https://elisa.fi/', '芬兰主要电信运营商，提供移动、宽带及数字服务，支持 eSIM 功能。'),
  ('https://www.sfr.fr/', '法国主要电信运营商之一，提供手机、宽带及旅行 SIM 套餐，网络覆盖全法。'),
  ('https://www.o2.co.uk/', '英国主要移动运营商，提供广泛的 4G/5G 覆盖，支持 eSIM 及优惠会员权益。'),
  ('https://ee.co.uk/', '英国最大移动运营商，5G 覆盖率领先，提供手机、宽带及企业通信服务。'),
  ('https://www.vodafone.co.uk/', '英国 Vodafone 分支，提供 4G/5G 移动服务、宽带及 eSIM，覆盖英国全境。'),
  ('https://www.vodafone.es/', '西班牙 Vodafone 分支，提供移动、宽带及电视套餐，网络质量优良。'),
  ('https://www.swisscom.ch/en', '瑞士最大电信运营商的预付套餐，网络质量全瑞士最佳，支持 eSIM 激活。'),
  ('https://www.vodafone.ua/', '乌克兰 Vodafone 分支，提供移动数据和语音服务，支持 eSIM 套餐购买。'),
  ('https://fizz.ca/en', '加拿大数字移动运营商，基于 Videotron 网络，提供灵活可定制的月租套餐。'),
  ('https://www.orange.be/fr', '比利时 Orange 分支，提供移动、宽带及电视服务，是比利时主要运营商之一。'),
  ('https://www.prd.base.be/en', '比利时 Telenet 旗下移动品牌，主打实惠套餐和灵活合约，适合预算有限用户。'),
  ('https://www.amaysim.com.au/', '澳大利亚 MVNO，基于 Optus 网络，提供无合约预付套餐，价格透明实惠。'),
  ('https://www.simyo.es/', '西班牙低价虚拟运营商，基于 Orange 网络，提供灵活的数据和通话套餐。'),
  ('https://www.lycamobile.pt/en', '葡萄牙 Lycamobile 分支，主打低价国际通话套餐，适合常打国际电话的用户。'),
  ('https://www.hot.si/', '斯洛文尼亚虚拟运营商，提供预付和后付移动套餐及 eSIM 服务。'),
  ('https://www.telia.fi/', '芬兰 Telia 分支，提供移动、宽带及 eSIM 服务，网络质量在芬兰名列前茅。'),
  ('https://www.simyo.nl/', '荷兰低价虚拟运营商，基于 KPN 网络，提供灵活无合约的移动数据套餐。'),
  ('https://www.nos.pt/', '葡萄牙主要电信运营商，提供移动、宽带、电视及企业通信一体化服务。'),
  ('https://mobile.free.fr/', '法国低价运营商，以极具竞争力的套餐价格著称，是法国四大运营商之一。'),
  ('https://eshop.t-mobile.cz/', '捷克 T-Mobile 分支，提供 4G/5G 移动服务及 eSIM 套餐，网络覆盖全国。'),
  ('https://lmt.lmt.lv/en', '拉脱维亚最大移动运营商，提供移动和宽带服务，5G 网络处于本地领先地位。'),
  ('https://www.orange.lu/en', '卢森堡 Orange 分支，提供移动预付套餐和 eSIM，是卢森堡主要运营商之一。'),
  ('https://www.kpn.com/', '荷兰最大电信运营商，提供移动、宽带和企业通信，网络基础设施覆盖全国。'),
  ('https://www.cuniq.jp/', '日本 MVNO 运营商，提供低价数据 SIM 套餐，适合在日外籍人士和游客使用。'),
  ('https://www.vodafone.pt/', '葡萄牙 Vodafone 分支，提供移动、宽带及企业通信服务，网络质量良好。'),
  ('https://www.vodafone.nl/', '荷兰 Vodafone 分支，现与 Ziggo 合并为 VodafoneZiggo，提供综合通信服务。'),
  ('https://www.o2online.de/', '德国 O2 运营商，Telefónica 旗下，提供手机、宽带及 eSIM 套餐服务。'),
  ('https://www.turkcell.com.tr/', '土耳其最大移动运营商，提供移动、数字服务及金融科技产品，用户超 4000 万。'),
  ('https://grok.com/', 'xAI 出品的 AI 助手，集成于 X（Twitter）平台，以幽默风格和实时联网能力著称。'),
  ('https://www.deepseek.com/', '中国领先 AI 大模型，以极低训练成本实现顶尖性能，开源模型在全球开发者中广受好评。'),
  ('https://chat.z.ai/', '多模型聚合 AI 对话平台，支持同时调用多个主流大模型进行对比和切换使用。'),
  ('https://www.coze.cn/', '字节跳动旗下 AI Bot 搭建平台，无需编程即可创建和发布 AI 机器人到多个平台。'),
  ('https://ollama.com/', '本地运行大模型的工具，支持 Llama、Mistral 等主流开源模型，部署简单，保护隐私。'),
  ('https://www.ai-suguan.com/', '国内 AI 工具聚合平台，提供多款主流大模型的统一入口和使用体验。'),
  ('https://huggingface.co/', '全球最大 AI 模型和数据集社区，提供模型托管、在线推理及机器学习工具库。'),
  ('https://www.modelscope.cn/', '阿里达摩院开源模型社区，提供数千个预训练模型的下载、体验和部署服务。'),
  ('https://opentherank.com/', 'AI 模型 API 价格对比平台，汇聚主流大模型的 Token 定价，帮助开发者选择最优方案。'),
  ('https://ai-bot.cn/', '中文 AI 工具导航站，汇聚国内外主流 AI 工具和大模型入口，分类清晰易于查找。'),
  ('https://zread.ai/', 'AI 辅助阅读工具，可快速总结长文、PDF 和网页内容，提升信息获取效率。'),
  ('https://smithery.ai/', 'MCP 服务器注册和发现平台，汇聚大量可供 AI 调用的工具和数据源，便于开发者接入。'),
  ('https://www.pulsemcp.com/', 'MCP 生态追踪平台，实时更新 MCP 服务器列表和社区动态，适合关注 AI 工具生态的开发者。'),
  ('https://mcp.directory/', 'MCP 服务器目录站，按分类收录可用的 MCP 工具，方便快速查找所需的 AI 集成服务。'),
  ('https://mcp.so/zh', '中文 MCP 工具聚合平台，收录大量 MCP 服务器，提供中文界面方便国内开发者使用。'),
  ('https://mcpmarket.com/zh', 'MCP 市场平台，提供 MCP 服务器的发现、安装和管理，支持中文界面。'),
  ('https://mcpservers.org/zh-CN', 'MCP 服务器中文目录，分类收录各类 MCP 工具，并提供安装说明和使用示例。'),
  ('https://skillsmp.com/zh', '技能服务平台，提供各类数字技能的学习资源和工具，支持中文界面使用。'),
  ('https://xszn.org/zh', '学生资源导航平台，收录适合在校学生使用的学习工具、资源和实用网站链接。'),
  ('https://devmaster.cn/', '开发者工具和资源导航，收录各类编程工具、框架文档和开发者社区链接。'),
  ('https://windsurf.com/', 'Codeium 出品的 AI 编程编辑器，深度集成 AI 辅助，支持多文件理解和代码生成。'),
  ('https://www.codeflicker.ai/', 'AI 编程辅助工具，提供智能代码补全和错误修复建议，提升编程效率。'),
  ('https://www.verdent.ai/', 'AI 软件工程平台，自动化处理代码审查、文档生成和测试编写等重复性开发任务。'),
  ('https://www.augmentcode.com/', '面向企业的 AI 编程平台，深度理解代码库上下文，提供精准的代码补全和重构建议。'),
  ('https://opencode.ai/', '开源 AI 编程工具，在终端中运行，支持多模型接入，适合喜欢命令行工作流的开发者。'),
  ('https://kiro.dev/', '亚马逊推出的 AI IDE，支持规格驱动开发，能自动生成需求文档、设计和代码。'),
  ('https://qoder.com/', 'AI 编程助手平台，帮助开发者加速编写、调试和理解代码，支持多种编程语言。'),
  ('https://www.withtap.com/', 'NFC 智能名片和社交资料分享工具，通过 NFC 碰一碰即可分享联系方式和社交账号。'),
  ('https://zero.co.uk/', '英国环保数字银行，提供碳足迹追踪功能，帮助用户了解消费对环境的影响。'),
  ('https://bolt.new/', 'StackBlitz 出品的 AI 全栈开发平台，在浏览器中即可生成、运行和部署完整应用。'),
  ('https://atoms.dev/', 'AI 驱动的开发者工具平台，提供组件生成和代码片段管理功能。'),
  ('https://suibian.org/', '随便导航平台，提供多类别工具和资源的快速访问入口，风格轻松随意。'),
  ('https://studio.tripo3d.ai/', 'AI 3D 模型生成工具，通过文字或图片描述即可快速生成高质量可用的 3D 模型。'),
  ('https://www.hitem3d.ai/zh', 'AI 驱动的 3D 内容创作平台，支持人物、场景等 3D 资产的快速生成和编辑。'),
  ('https://bobtranslate.com/', 'macOS 翻译和 OCR 工具，支持划词翻译、截图翻译，可接入多种翻译 API 引擎。'),
  ('https://easyvoice.ioplus.tech/', '在线文字转语音工具，提供多种语言和音色选择，可将文本快速转换为自然语音。'),
  ('https://magicv.art/zh', 'AI 视频和图像创作工具，支持文生图、图生视频等功能，面向内容创作者使用。'),
  ('https://zh.bgsub.com/', 'AI 自动抠图和背景替换工具，处理速度快，在浏览器本地运行保护隐私，免费使用。'),
  ('https://edigitalchoice.com/', '数字产品和软件推荐平台，提供各类软件工具的评测和比较，帮助用户做出最佳选择。'),
  ('https://skillhub.cn/', '技能学习资源导航，汇聚各类编程、设计和职业技能的优质学习资源和教程。'),
  ('https://www.spaceship.com/zh', 'Namecheap 旗下新品牌，提供域名注册和云主机服务，界面简洁，定价有竞争力。'),
  ('https://regery.com/en', '乌克兰域名注册商，支持大量 ccTLD 和 gTLD，提供有竞争力的域名定价。'),
  ('https://www.godaddy.com/', '全球最大域名注册商，提供域名、主机、建站和企业邮箱等全套互联网服务。'),
  ('https://www.namesilo.com/', '美国低价域名注册商，永久免费 WHOIS 隐私保护，价格透明无续费陷阱。'),
  ('https://www.namecheap.com/', '美国知名域名注册商，价格实惠，提供免费 WhoisGuard 隐私保护和主机服务。'),
  ('https://www.dynadot.com/zh', '美国域名注册商，界面支持中文，价格有竞争力，提供域名交易市场和建站工具。'),
  ('https://porkbun.com/', '美国新兴域名注册商，新域名价格极具竞争力，免费提供 WHOIS 隐私和 SSL 证书。'),
  ('https://www.cosmotown.com/', '新兴域名注册商，提供透明定价和友好界面，支持常见顶级域名注册。'),
  ('https://www.inwx.com/en', '德国域名注册商，支持大量顶级域名，价格实惠，提供 API 接口方便批量管理。'),
  ('https://www.internetx.com/', '德国企业级域名和 SSL 证书提供商，支持 1000+ 种 TLD，提供 API 和批量管理工具。'),
  ('https://marketing.sav.com/zh', '域名注册和管理平台，提供有竞争力的域名定价及批量管理工具。'),
  ('https://smartdomain.io/zh', '智能域名搜索和注册工具，支持中文界面，可跨多家注册商比价后一键购买。'),
  ('https://nic.ua/en', '乌克兰官方域名注册机构，负责 .ua 国家域名注册管理，提供多种顶级域名服务。'),
  ('https://namebeta.com/', '域名可用性查询和比价工具，实时检索多家注册商价格，方便选择最优注册渠道。'),
  ('https://zh-hant.tld-list.com/', '全球顶级域名信息汇总平台，提供 TLD 价格对比、注册商推荐及域名政策查询。'),
  ('https://www.nazhumi.com/', '中文域名查询和比价工具，支持多家注册商价格对比，帮助用户找到最划算的注册渠道。'),
  ('https://www.getfreedomain.name/', '免费域名注册平台，提供多种后缀的免费域名，适合个人网站和测试项目使用。'),
  ('https://freedomain.one/', '提供免费顶级域名注册服务，无需付费即可获得真正的顶级域名用于个人网站。'),
  ('https://www.dynu.com/zh-CN', '免费动态 DNS 服务，支持自定义域名和免费子域名，适合家庭服务器和个人项目。'),
  ('https://ydns.io/', '免费动态 DNS 服务，提供自定义子域名和 API 更新支持，适合家庭网络使用。'),
  ('https://my.zone.id/', '印度尼西亚域名注册平台，提供 .id 国家域名及其他顶级域名注册和 DNS 管理。'),
  ('https://dash.domain.digitalplat.org/', '域名注册和管理平台，提供简洁的管理面板，支持多种顶级域名。'),
  ('https://dash.cloudflare.com/', '全球领先的 CDN 和网络安全服务商，同时提供域名注册、DNS 和 Zero Trust 安全产品。'),
  ('https://www.cloudns.net/', '全球 DNS 托管服务，提供免费和付费 DNS 解析，支持 Anycast 网络加速。'),
  ('https://www.hetzner.com/', '德国知名云服务商，以极高性价比著称，提供独立服务器、VPS 和对象存储，深受开发者喜爱。'),
  ('https://contabo.com/', '德国低价 VPS 和独立服务器提供商，配置高存储大，价格在欧洲市场极具竞争力。'),
  ('https://upcloud.com/', '芬兰云服务商，以 MaxIOPS 高性能存储和稳定网络著称，多个欧洲数据中心可选。'),
  ('https://www.scaleway.com/en', '法国云服务商，Iliad 集团旗下，提供 VPS、裸金属、Kubernetes 和无服务器产品。'),
  ('https://www.time4vps.com/', '立陶宛低价 VPS 提供商，价格实惠，适合欧洲节点的个人网站和小型应用部署。'),
  ('https://www.racknerd.com/', '美国低价 VPS 提供商，经常推出促销套餐，适合个人项目和小型网站部署。'),
  ('https://my.vultr.com/', '美国全球云服务商，在全球 30+ 个地点提供 VPS、裸金属和 Kubernetes 服务，部署快速。'),
  ('https://www.leaseweb.com/en', '荷兰企业级托管服务商，提供独立服务器、VPS 和私有云，注重高带宽和网络稳定性。'),
  ('https://www.ovhcloud.com/en', '法国最大云服务商之一，提供 VPS、独立服务器和公有云，数据中心遍布全球。'),
  ('https://www.ionos.de/', '德国知名主机商，提供虚拟主机、VPS 和云服务器，在欧洲和美国均有数据中心。'),
  ('https://www.strato.de/', '德国老牌主机商，提供虚拟主机、VPS 和域名注册服务，用户群以德国企业为主。'),
  ('https://digvps.com/', '国人运营的 VPS 服务商，提供多个数据中心节点，适合需要稳定出口线路的用户。'),
  ('https://www.prolxy.com/', '代理和 VPS 服务提供商，提供住宅代理和数据中心 IP 资源，适合爬虫和隐私保护场景。'),
  ('https://www.uqidc.com/', '国内云服务和 IDC 托管服务商，提供香港、美国等节点的 VPS 和独立服务器。'),
  ('https://hostfe.com/', 'VPS 托管服务提供商，提供多地区节点和灵活配置，面向个人和企业用户。'),
  ('https://vercel.com/', '前端部署首选平台，与 Next.js 深度集成，支持 Git 自动部署、CDN 加速和无服务器函数。'),
  ('https://www.netlify.com/', '静态站点和 JAMstack 应用托管平台，支持 CI/CD 自动部署、表单处理和边缘函数。'),
  ('https://fly.io/', '全球分布式应用托管平台，将 Docker 容器部署至全球边缘节点，延迟低，开发者体验好。'),
  ('https://render.com/', '简单易用的云应用托管平台，支持 Web 服务、数据库、定时任务和静态站点一站式部署。'),
  ('https://zeabur.com/', '面向开发者的一键部署平台，支持多种框架和数据库，简化从代码到上线的全流程。'),
  ('https://cloud.tencent.com/', '腾讯云，国内主流云服务商，提供计算、存储、数据库及 AI 服务，生态完善。'),
  ('https://www.tencentcloud.com/zh', '腾讯云国际版，面向海外用户提供全球数据中心的云计算服务，支持多语言界面。'),
  ('https://www.jdcloud.com/', '京东云，国内云服务商，提供 IaaS、PaaS 及企业数字化解决方案，与京东生态深度集成。'),
  ('https://www.hostinger.com/hk', '立陶宛主机商，以超低价格提供虚拟主机、VPS 和域名，是全球最大主机商之一。'),
  ('https://www.hostinger.com/', '立陶宛主机商，以超低价格提供虚拟主机、VPS 和域名，是全球最大主机商之一。'),
  ('https://aiven.io/', '托管开源数据服务平台，提供 PostgreSQL、Redis、Kafka 等云数据库，支持多云部署。'),
  ('https://console.leancloud.app/', '国内云后端服务平台，提供数据存储、即时通讯、推送等 BaaS 服务，常用于博客评论。'),
  ('https://www.superbed.cc/', '聚合图床工具，支持将图片同时上传到多个图床平台，防止图床跑路导致图片失效。'),
  ('https://www.superbed.cn/', '聚合图床工具，支持将图片同时上传到多个图床平台，防止图床跑路导致图片失效。'),
  ('https://akirabox.com/', '开源软件和工具资源导航站，收录各类实用工具和应用程序，分类清晰便于查找。'),
  ('http://pcloud.com/', '瑞士云存储服务，提供 10GB 免费空间和终身套餐选项，支持端到端加密，注重隐私。'),
  ('https://drime.cloud/', '法国云存储服务，数据存储于法国本土，符合 GDPR，注重数据主权和隐私保护。'),
  ('https://mega.nz/', '新西兰加密云存储，提供 20GB 免费空间和端到端加密，支持大文件分享链接。'),
  ('https://blazeb2.js.org/', '基于 Backblaze B2 的图床工具，将 B2 存储与 Cloudflare CDN 结合，实现低成本图片托管。'),
  ('https://mail.google.com/', '谷歌旗下全球最大的免费邮件服务，与 Google 工作区深度集成，提供 15GB 免费存储。'),
  ('https://outlook.live.com/', '微软旗下邮件服务，与 Office 365 生态集成，支持日历、联系人及多账号统一管理。'),
  ('https://mail.yahoo.com/', '雅虎邮件，老牌免费邮箱，提供 1TB 存储空间，支持多账号聚合管理。'),
  ('https://mail.aol.com/', 'AOL 免费邮件服务，界面简洁，提供无限存储，在北美地区仍有一定用户基础。'),
  ('https://mail.zoho.com/', '印度 SaaS 公司 Zoho 提供的企业邮件服务，无广告，与 Zoho 办公套件深度集成。'),
  ('https://account.proton.me/zh-cn', '瑞士端对端加密邮箱，无日志政策，服务器位于瑞士，是目前最受信赖的隐私邮箱之一。'),
  ('https://mail.yandex.com/', '俄罗斯最大互联网公司 Yandex 提供的邮件服务，支持多语言，在俄语区广泛使用。'),
  ('https://www.gmx.com/', '德国免费邮件服务，提供无限存储，支持 IMAP/POP3，在欧洲尤其德语区使用广泛。'),
  ('https://www.mail.com/', '提供 200+ 个性化域名后缀选择的免费邮箱，支持多账号聚合管理，全球用户均可注册。'),
  ('https://web.de/', '德国主流免费邮箱，与 GMX 同属 United Internet，提供德语界面和本地化邮件服务。'),
  ('https://5x2.de/', '德国免费邮箱服务，提供简洁的 Webmail 界面，注重数据存储在德国本地保护隐私。'),
  ('https://x-mail.plus/', '注重隐私的邮件服务，提供加密邮箱和临时邮件功能，适合保护个人通信隐私。'),
  ('https://mail.de/de', '德国隐私邮箱，数据存储于德国本土，符合严格的欧洲数据保护法规，提供加密选项。'),
  ('https://mail.co.uk/en', '英国域名后缀邮箱服务，提供以 .co.uk 结尾的邮件地址，面向英国用户。'),
  ('https://atomicmail.io/', '隐私优先的加密邮件服务，支持匿名注册和端到端加密，保护邮件内容不被第三方访问。'),
  ('https://firemail.de/', '德国隐私邮件服务，服务器位于德国，符合 GDPR，提供加密邮箱和匿名注册选项。'),
  ('https://www.eclipso.ch/', '瑞士邮件服务，提供安全加密的邮箱账户，数据存储于瑞士，符合严格隐私标准。'),
  ('https://murena.io/', '/e/ 基金会提供的隐私云服务，提供去谷歌化邮箱、日历和文件存储，注重数据主权。'),
  ('https://webmail.disroot.org/', '去中心化隐私服务平台，提供邮件、云存储和论坛等服务，由社区志愿者运营。'),
  ('https://manager.infomaniak.com/', '瑞士独立云服务商，提供邮箱、云存储、建站等服务，强调数据主权和可持续发展。'),
  ('https://accounts.freemail.hu/', '匈牙利最受欢迎的免费邮件服务之一，提供匈牙利语界面，深受本地用户喜爱。'),
  ('https://login.szn.cz/', '捷克门户网站 Seznam 旗下邮件服务，是捷克最主流的本地邮箱之一。'),
  ('https://poczta.onet.pl/', '波兰最大门户网站 Onet 旗下免费邮箱，是波兰用户最常用的邮件服务之一。'),
  ('https://poczta.o2.pl/', '波兰主流免费邮件服务之一，提供简洁的 Webmail 界面和基础邮件收发功能。'),
  ('https://poczta.wp.pl/', '波兰门户网站 Wirtualna Polska 旗下邮箱，在波兰用户群体中使用较为普遍。'),
  ('https://mail.bg/', '保加利亚主流免费邮件服务，提供以 .bg 后缀为主的邮箱，面向保加利亚用户。'),
  ('https://mail.sapo.pt/', '葡萄牙老牌门户 SAPO 提供的免费邮件服务，在葡萄牙用户中有较高知名度。'),
  ('https://mail.daum.net/', '韩国门户网站 Daum（现 Kakao 旗下）提供的免费邮件服务，在韩国有大量用户。'),
  ('https://mail.kakao.com/', '韩国最大即时通讯平台 KakaoTalk 推出的邮件服务，与 Kakao 账号绑定，在韩国广泛使用。'),
  ('https://www.inbox.lv/', '拉脱维亚主流邮件服务，同时覆盖立陶宛、爱沙尼亚等波罗的海国家用户。'),
  ('https://www.mail.ee/', '爱沙尼亚本地邮件服务，提供以 .ee 为后缀的邮箱地址，面向爱沙尼亚用户。'),
  ('https://e.mail.ru/', '俄罗斯最大邮件服务之一，VK 集团旗下，提供免费邮箱和云存储，在俄语区极为普及。'),
  ('https://vk.mail.ru/', 'VK 社交平台集成的邮件服务，与 VK 账号绑定，方便俄语区用户统一管理通信。'),
  ('https://mail.rambler.ru/', '俄罗斯老牌门户网站旗下邮箱，在俄语区有一定用户基础，提供基础邮件功能。'),
  ('https://mail.sibnet.ru/', '俄罗斯西伯利亚地区互联网服务商旗下邮箱，提供免费个人邮件账户服务。'),
  ('https://xmail.net/', '免费邮件服务平台，提供多种域名后缀选择，支持基础邮件收发和 Webmail 访问。'),
  ('https://accounts.ukr.net/', '乌克兰主流免费邮箱和门户网站，提供稳定的邮件服务，在乌克兰用户中广泛使用。'),
  ('https://www.aikq.de/', '德国免费邮件服务，提供以 .de 为后缀的邮箱地址，面向德语用户群体。'),
  ('https://www.mailo.com/', '法国独立邮件服务，注重隐私保护，数据存储于法国，提供无广告的纯净邮件体验。'),
  ('https://mail.vodafone.de/', '德国 Vodafone 电信运营商提供的邮件服务，适合 Vodafone 德国客户使用。'),
  ('https://tinkmail.me/', '隐私邮件服务，提供安全加密的邮箱账户，支持匿名注册，保护用户身份信息。'),
  ('https://astermail.org/', '隐私导向的邮件服务，提供加密邮箱账户，适合注重个人通信隐私的用户使用。'),
  ('https://pissmail.com/', '免费匿名邮箱服务，提供随机或自定义地址，适合不想暴露真实邮箱的临时使用场景。'),
  ('https://mailum.com/', '注重隐私的加密邮件服务，支持端到端加密和匿名注册，保护用户通信内容不被窥探。'),
  ('https://iredmail.org/', '开源邮件服务器解决方案，支持自建邮件系统，集成 Postfix、Dovecot 等组件。'),
  ('https://wx.mail.qq.com/', '腾讯 QQ 邮箱，国内主流邮箱之一，与 QQ 和微信生态绑定，支持超大附件发送。'),
  ('https://mail.163.com/', '网易 163 邮箱，国内最主流的免费邮箱之一，稳定可靠，支持 SMTP/IMAP 协议。'),
  ('https://www.126.com/', '网易 126 邮箱，与 163 同属网易旗下，提供免费稳定的个人邮件服务。'),
  ('https://yeah.net/', '网易旗下邮箱品牌之一，提供个人免费邮箱服务，与 163 和 126 共享网易邮件系统。'),
  ('https://mail.aliyun.com/', '阿里云邮箱，提供免费个人版和付费企业版，与阿里云生态集成，安全稳定。'),
  ('https://m1.mail.sina.com.cn/', '新浪邮箱，国内邮件服务，与新浪微博账号绑定，提供免费个人邮件收发功能。'),
  ('https://www.enginemailer.com/', '邮件营销发送平台，提供批量邮件发送、列表管理和数据分析功能，适合中小企业使用。'),
  ('https://www.mail-signatures.com/', '在线邮件签名生成工具，提供多种专业模板，可添加 Logo、社交链接和头像。'),
  ('https://beefree.io/', '在线邮件模板编辑器，提供大量精美的拖拽式邮件模板，方便快速设计营销邮件。'),
  ('https://www.mailmodo.com/', '互动式邮件模板平台，支持在邮件内嵌入表单、调查问卷等互动元素，提升邮件转化率。'),
  ('https://stripo.email/', '专业邮件模板设计平台，提供 1000+ 套模板和可视化编辑器，支持导出到主流 ESP。'),
  ('https://www.notion.com/', 'Notion 推出的智能邮件客户端，与 Notion 工作区深度集成，支持 AI 辅助邮件处理。'),
  ('https://www.smspool.net/', '虚拟号码接码服务，提供全球多国号码，支持主流平台验证，价格透明，有 API 接口。'),
  ('https://sms-activate.guru/cn', '全球最大虚拟号码接码平台，支持 700+ 个服务验证码接收，覆盖数十个国家的手机号。'),
  ('https://5sim.net/zh', '在线虚拟号码服务，提供多国临时手机号用于注册验证，支持多种服务和灵活计费。'),
  ('https://onlinesim.io/', '虚拟号码接码服务，提供多国手机号租用，支持长期号码和一次性验证码接收。'),
  ('https://sms-man.com/cn', '全球虚拟号码平台，价格实惠，支持主流互联网平台的注册验证码接收。'),
  ('https://grizzlysms.com/cn', '虚拟手机号码服务，提供多国号码用于一次性验证，支持各类主流平台注册。'),
  ('https://tiger-sms.com/cn', '在线接码平台，提供多国虚拟号码，按条计费，适合批量账号注册验证使用。'),
  ('https://daputao.me/', '中文接码服务平台，提供国内外虚拟号码，支持主流中国互联网平台注册验证。'),
  ('https://2024sms.com/', '在线免费接码工具，提供公共虚拟号码用于接收验证短信，适合临时使用场景。'),
  ('https://icon.kitchen/', '应用图标生成工具，支持为 Android、iOS 和 Web 一键生成各种尺寸规格的应用图标。'),
  ('https://yesicon.app/', '中文图标搜索引擎，聚合 200+ 套图标库共 18 万个图标，支持中文关键词搜索。'),
  ('https://iconbuddy.com/', '开源 SVG 图标搜索和定制工具，支持修改颜色、大小和下载格式，免费商用。'),
  ('https://icons8.com/', '大型图标和设计资源平台，提供百万级图标、插图、照片和音效，部分免费可商用。'),
  ('https://lucide.dev/', 'Feather Icons 的社区延伸版，提供 1000+ 个简洁一致的 SVG 图标，支持多框架。'),
  ('https://ionic.io/', 'Ionic 框架出品的开源图标库，提供 1300+ 个 SVG 图标，适用于 Web 和移动端项目。'),
  ('https://remixicon.com/', '开源图标系统，提供 2800+ 个精心设计的图标，分线性和填充两种风格，免费商用。'),
  ('https://www.xicons.org/', '多图标库聚合平台，整合 Font Awesome、Material 等主流图标库，统一搜索和使用。'),
  ('https://www.itshover.com/', '交互式图标集合，提供带悬停动画效果的图标组件，适合为网页增加生动的视觉交互。'),
  ('https://fontlogo.site/', '字体 Logo 生成工具，通过组合字体和图形快速生成文字型 Logo，适合品牌初期设计。'),
  ('https://uiverse.io/', '社区驱动的 UI 元素分享平台，提供大量纯 CSS 和 Tailwind 实现的按钮、卡片等组件。'),
  ('https://reactbits.dev/', 'React 动画组件库，提供丰富的交互动效组件，适合快速为 React 应用添加视觉亮点。'),
  ('https://magicui.design/', '面向 React 的动效 UI 组件库，专注于精美动画效果，与 shadcn/ui 风格兼容。'),
  ('https://spark-ui.dev/', '现代化 UI 组件库，提供一套设计精良的 React 组件，注重开发体验和可定制性。'),
  ('https://vue-bits.dev/', 'Vue 动画组件集合，提供精美的 UI 动效组件，直接复制代码即可用于 Vue 项目。'),
  ('https://finalui.com/', '高质量 UI 组件和模板集合，提供精美的设计资源，适合快速构建现代化 Web 界面。'),
  ('https://www.ui-layouts.com/', '现代 UI 布局组件集合，提供响应式布局模板和组件，可直接用于 Tailwind 项目。'),
  ('https://refero.design/', '设计灵感参考平台，收录真实产品的设计截图，按功能和风格分类，便于查找设计参考。'),
  ('https://v8.mantine.dev/', '功能完善的 React 组件库，提供 100+ 个高质量组件和 Hook，文档详尽易于使用。'),
  ('https://longbridge.github.io/', '基于 Rust GPUI 框架的 UI 组件库，为使用 GPUI 构建桌面应用的开发者提供现成组件。'),
  ('https://themusecatcher.github.io/', 'Vue 3 UI 组件库，提供丰富的业务组件，风格简洁，适合中后台管理系统开发。'),
  ('https://sweezy-cursors.com/', '自定义鼠标光标资源站，提供大量精美的鼠标指针包，可下载安装个性化桌面体验。'),
  ('https://www.algolia.com/', '全球领先的搜索即服务平台，提供毫秒级全文搜索 API，广泛用于文档站和电商网站。'),
  ('https://htmlrev.com/', '免费 HTML 模板集合站，提供各类高质量的落地页、管理后台和个人网站模板下载。'),
  ('https://themeforest.net/', 'Envato 旗下全球最大的网站模板市场，提供数万套 WordPress、HTML 及各类框架主题。'),
  ('https://statichunt.com/', '静态站点主题和模板目录，汇聚 Gatsby、Next.js、Hugo 等框架的免费和付费主题。'),
  ('https://www.builtatlightspeed.com/', '现代 Web 主题和模板目录，专注 Astro、SvelteKit 等新兴框架的优质模板收录。'),
  ('https://jamstack.org/', 'JAMstack 静态站点生成器目录，汇聚 Gatsby、Hugo、Astro 等框架的介绍和对比。'),
  ('https://frontresources.dev/', '前端开发资源导航，整合优质工具、库、教程和设计资源，方便开发者快速查阅。'),
  ('https://app.freelogodesign.org/', '在线免费 Logo 设计工具，提供大量模板和图标，无需设计经验即可制作专业 Logo。'),
  ('https://www.pling.com/', '开源社区作品分享平台，提供 Linux 主题、图标包、Android 壁纸等开源创意内容。'),
  ('https://vitepress.dev/zh', 'Vue 官方静态站点生成器，基于 Vite 构建，专为文档网站设计，性能极佳。'),
  ('https://vitepress.catppuccin.com/', '为 VitePress 提供 Catppuccin 配色方案的主题插件，让文档站拥有柔和优雅的视觉风格。'),
  ('https://vitepress.yiov.top/', 'VitePress 中文建站教程和资源站，提供详细的配置指南和常用插件推荐。'),
  ('https://theme.sugarat.top/', '基于 VitePress 的博客主题，界面简洁美观，支持文章分类、评论和自定义样式。'),
  ('https://www.bestvuepressthemes.com/', 'VuePress 主题精选目录，汇聚社区中最受欢迎的 VuePress 博客和文档主题。'),
  ('https://doc.xugaoyi.com/', 'vdoing 主题作者的文档站，提供该 VuePress 知识管理主题的完整使用文档和示例。'),
  ('https://vp.yuy1n.io/', 'VitePress 自定义主题，提供独特的视觉风格和增强功能，适合个人博客和文档站使用。'),
  ('https://nolebase-integrations.ayaka.io/', 'VitePress 插件集合，提供增强阅读体验、Git 提交信息展示等实用功能扩展。'),
  ('https://rspress.rs/zh', '基于 Rspack 的高性能静态站点生成器，构建速度极快，适合大型文档项目。'),
  ('https://theme-reco.vuejs.press/', 'Vue 驱动的博客主题，功能完善，支持分类、标签、评论和时间轴等博客常见功能。'),
  ('https://lumen.theojs.cn/', 'VitePress 增强主题，在默认主题基础上添加了博客功能和精美样式，开箱即用。'),
  ('https://hexo-theme-async.imalun.com/', 'Hexo 博客主题，设计简洁现代，支持多种配色方案和丰富的配置选项。'),
  ('https://solitude.js.org/cn', '优雅的 Hexo 博客主题，界面精美，支持暗黑模式、音乐播放器和多种页面组件。'),
  ('https://docs.anheyu.com/', 'AnZhiYu Hexo 主题的官方文档，提供主题安装、配置和美化的详细教程。'),
  ('https://pagescms.org/', '基于 Git 的无头 CMS，为静态站点提供可视化内容管理界面，无需搭建后端服务。'),
  ('https://docs.orama.com/', '开源全文搜索引擎，可在浏览器和 Node.js 中运行，无需外部服务即可实现本地搜索。'),
  ('https://waline.js.org/', '安全的开源评论系统，从 Valine 衍生，支持多种数据库后端和邮件通知功能。'),
  ('https://twikoo.js.org/', '简洁优雅的博客评论系统，基于云函数部署，支持表情、图片和邮件通知。'),
  ('https://valine.js.org/', '快速无后端评论系统，基于 LeanCloud，配置简单，适合静态博客快速接入评论功能。'),
  ('https://gitalk.github.io/', '基于 GitHub Issues 的评论插件，利用 GitHub 账号登录，数据存储在 GitHub 仓库中。'),
  ('https://artalk.js.org/', '自托管评论系统，功能丰富，支持多站点管理、审核和多种后端数据库存储。'),
  ('https://vssue.js.org/', '支持多种 Git 平台的评论插件，可使用 GitHub、GitLab 等账号登录发表评论。'),
  ('https://bsr.xinrea.cn/', '基于 VitePress 的博客主题，提供简洁的博客功能和良好的阅读体验。'),
  ('https://capsule-render.vercel.app/', 'GitHub README 动态头图生成工具，支持多种样式和颜色，美化个人或项目主页。'),
  ('https://readme-typing-svg.demolab.com/', '生成打字机效果 SVG 动画的工具，常用于 GitHub Profile README 动态文字展示。'),
  ('https://tauri.app/zh-cn', '使用 Web 技术构建轻量级跨平台桌面应用的框架，相比 Electron 体积更小性能更好。'),
  ('https://www.ilovepdf.com/zh-cn', '在线 PDF 处理工具集，支持合并、拆分、压缩、转换等 20+ 种 PDF 操作，免费使用。'),
  ('https://pdftranslator.org/zh', '在线 PDF 翻译工具，支持将 PDF 文档内容翻译成多种语言，保留原始排版格式。'),
  ('https://www.qr-code-generator.com/', '在线二维码生成工具，支持 URL、文本、名片等多种格式，可自定义颜色和 Logo。'),
  ('https://text-to-handwriting.org/zh', '将打印文字转换为手写风格图片的工具，可选择不同字体和纸张样式，模拟真实手写效果。'),
  ('https://handwrite.sixiangjia.de/', '在线手写字体转换工具，将数字文字转换为手写风格，适合制作手写笔记或作业图片。'),
  ('https://cv-template.online/', '在线简历模板工具，提供多种专业简历设计，支持在线编辑和导出为 PDF 格式。'),
  ('https://addressgen.top/zh', '随机地址生成工具，可生成虚假的真实格式地址，适用于需要填写地址但不想暴露真实信息的场景。'),
  ('https://whoer.net/zh', '在线 IP 和隐私检测工具，显示当前 IP 地址、DNS 泄漏、浏览器指纹等隐私信息。'),
  ('https://scamalytics.com/', 'IP 欺诈评分检测工具，检测某个 IP 地址的风险等级和是否被标记为代理或 VPN 节点。'),
  ('https://veriftools.net/', '在线验证工具集，提供邮箱、手机号、IP 等信息的有效性检测和格式验证功能。'),
  ('https://icp.redcha.cn/', '国内网站 ICP 备案查询工具，可快速检索某个域名或网站的备案主体和状态信息。'),
  ('https://icp.gov.moe/', '萌 ICP 备案平台，为个人网站提供非官方的趣味性 ICP 备案服务，仅供娱乐用途。'),
  ('https://tableplus.com/', '现代化数据库管理工具，支持 MySQL、PostgreSQL、SQLite 等多种数据库，界面简洁美观。'),
  ('https://marktext.me/', '开源跨平台 Markdown 编辑器，所见即所得，界面简洁，支持多种主题和导出格式。'),
  ('https://massgrave.dev/', '开源 Windows 和 Office 激活工具项目，提供多种合法激活方案，使用广泛安全可靠。'),
  ('https://www.psdstencil.cc/', '在线 PSD 模板和设计素材库，提供各类 Mockup 模板，方便展示设计作品效果。'),
  ('https://rue.ee/cn', '欧洲最大新型银行资讯文章，分析 Revolut、N26 等欧洲主流数字银行的规模和特点。'),
  ('https://www.maoken.com/', '中文字体下载和资讯平台，收录大量免费可商用中文字体，并提供字体授权信息说明。'),
  ('https://lizhi.shop/', '数字产品和软件授权购买平台，提供各类正版软件激活码和数字服务的购买渠道。'),
  ('https://apsgo.com/', '应用程序下载和推荐平台，收录各类移动端和桌面端优质应用，提供简洁的下载入口。'),
  ('https://aibijia.org/', 'AI 工具比价和测评平台，汇聚主流 AI 产品定价和功能对比，帮助用户做出最优选择。'),
  ('https://moneyzine.com/', '个人理财资讯网站，提供银行账户、信用卡、贷款和投资产品的比较和评测内容。'),
  ('https://nav.nbw.one/', '个人导航站，收录各类常用工具和资源链接，按分类整理便于日常快速访问。'),
  ('https://www.openpgp.org/', '开源邮件和数据加密标准，提供 PGP 加密工具和软件目录，用于保护通信内容安全。'),
  ('https://regtons.com/en', '域名注册服务商，提供多种顶级域名注册，注重隐私保护和简洁用户体验。'),
  ('https://www.tiptrans.com/', '国际转运服务，提供美国、英国等地收货地址，支持将包裹整合后转寄至全球目的地。'),
  ('https://www.shipito.com/zh', '美国知名转运服务商，提供美国收货地址，支持包裹整合、照片确认和全球配送。'),
  ('https://www.jchere.com/', '日本转运和代购服务，提供日本地址和集运服务，支持亚马逊日本等平台商品转寄。'),
  ('https://www.anytimemailbox.com/', '美国虚拟邮箱服务，提供实体邮件数字化扫描，随时随地在线查看和管理纸质邮件。'),
  ('https://doc.veridocs.cc/', '文件验证和公证服务平台，提供证件认证、学历验证及文件公正等服务，面向海外用户。'),
  ('https://client.ipostalmail.net/', '美国虚拟地址和邮件管理服务，提供实体地址用于商业注册和邮件数字化处理。'),
  ('https://www.skypax.com/', '英国转运服务，提供英国收货地址，支持包裹合并和转寄到全球各地，适合海淘英国商品。'),
  ('https://www.royalmail.com/', '英国皇家邮政，英国官方邮政服务机构，提供国内和国际包裹寄送及快递跟踪服务。'),
  ('https://macwk.cn/', 'Mac 软件下载站，提供常用 macOS 软件的破解和正版资源，更新较为及时。'),
  ('https://sysin.org/', '系统和软件技术分享博客，提供 macOS、虚拟机和系统工具的使用教程及资源下载。'),
  ('https://www.macbl.com/', 'macOS 软件分享社区，提供各类 Mac 应用的下载资源，涵盖设计、开发和效率工具。'),
  ('https://appstorrent.ru/', '俄语区 Mac 软件下载站，提供大量 macOS 应用的免费下载，更新频繁内容丰富。'),
  ('https://appstorrent.org/', 'Mac 软件下载平台，提供 macOS 应用的免费下载资源，与 appstorrent.ru 内容相近。'),
  ('https://www.macdo.cn/', 'Mac 软件下载平台，提供正版和破解 macOS 应用资源，界面简洁操作方便。'),
  ('https://macked.app/', 'macOS 应用分享网站，提供各类 Mac 软件的免费下载，包含常用的付费软件资源。'),
  ('https://www.macupdate.com/', '老牌 Mac 软件目录和更新追踪平台，提供软件下载、评测和版本更新通知服务。'),
  ('https://www.waerfa.com/', '中文 Mac 软件评测和下载网站，提供详细的软件介绍和使用教程，面向中文用户。'),
  ('https://indiegoodies.com/', '独立开发者产品导航，收录精选的独立开发者制作的 macOS 和 iOS 应用工具。'),
  ('https://sspai.com/', '少数派，专注效率工具和数字生活的中文媒体，提供 Mac、iOS 应用评测和使用技巧。'),
  ('https://www.yyczxt.com/', '音乐创作软件资源站，提供 DAW、插件和采样包等音乐制作软件的下载和教程。'),
  ('https://winnew.cn/', 'Windows 软件资源和教程分享平台，提供系统优化、装机工具和常用软件下载资源。'),
  ('https://zhuangit.ababtools.com/', '装机和 IT 工具资源导航，提供系统安装、驱动程序和常用软件的下载链接汇总。'),
  ('https://distrowatch.com/', 'Linux 发行版追踪平台，提供各发行版的热度排名、新闻、版本历史和下载链接。'),
  ('https://pixelos.net/', '基于 AOSP 的类原生 Android ROM，提供接近 Pixel 体验，注重简洁和性能优化。'),
  ('https://crdroid.net/', '功能丰富的自定义 Android ROM，基于 LineageOS，提供大量 UI 自定义选项和性能优化。'),
  ('https://wiki.lineageos.org/', '最流行的开源 Android 发行版，支持大量设备，提供纯净无广告的 Android 体验。'),
  ('https://get.pixelexperience.org/', '模拟 Google Pixel 手机体验的 Android ROM，内置 GApps，提供原汁原味的 Pixel UI。'),
  ('https://lmo.framer.website/', '轻量级定制 Android ROM，注重性能和流畅度，提供干净的原生 Android 体验。'),
  ('https://xdaforums.com/', '全球最大的 Android 开发者和刷机论坛，提供 ROM、内核、工具和技术讨论资源。'),
  ('https://www.apkmirror.com/', '免费合法的 Android APK 下载站，收录历史版本 APK，由 Android Police 团队运营维护。'),
  ('https://hellogithub.com/', '分享有趣、入门级 GitHub 开源项目的月刊平台，帮助开发者发现值得关注的优质开源项目。'),
  ('https://fmhy.net/', '免费资源大全导航站，整合全网各类免费工具、软件、学习资源，分类详细内容丰富。'),
  ('https://nav.qixinpro.com/', '工具导航站，汇聚各类在线工具和资源，适合开发者和设计师日常使用查阅。'),
  ('https://www.miao3.cn/', '猫咪主题导航和资源站，提供各类有趣工具和网站的收录，风格轻松活泼。'),
  ('https://navnav.co/', '导航设计灵感网站，专门收录各类创意导航栏设计案例，供前端开发和设计师参考。'),
  ('https://www.weiyangx.com/', '微养社区，专注金融科技和互联网金融领域的资讯、研究报告和行业讨论平台。'),
  ('https://www.gachago.net/zh-cn', '扭蛋和盲盒相关资讯和购买平台，面向扭蛋文化爱好者提供商品信息和购买渠道。'),
  ('https://biliuniverse.io/', 'B 站相关工具或第三方平台，提供与哔哩哔哩生态相关的扩展功能和内容服务。'),
  ('https://milkup.dev/', '轻量级 Markdown 编辑器组件，可嵌入 Web 应用，提供实时预览和工具栏支持。'),
  ('https://yiguess.top/', '在线猜词/猜图小游戏平台，适合好友聚会和团队互动，支持多人在线同时参与游玩。'),
  ('https://www.crossdesk.cn/', '跨境工作和远程办公资源平台，提供面向跨境从业者的工具、资讯和服务推荐。'),
  ('https://xszn.org/', '学生资源导航平台，收录适合在校学生使用的学习工具、资源和实用网站链接。'),
  ('https://buff.163.com/', '网易旗下 CS2、DOTA2 等游戏饰品交易平台，国内最大的游戏道具交易市场之一。'),
  ('https://www.youpin898.com/', '国内游戏饰品交易平台，支持 CS2、DOTA2 等多款游戏道具的买卖，手续费低。'),
  ('https://steamcommunity.com/', 'Steam 社区市场，用于玩家之间买卖游戏道具、皮肤和集换式卡片，交易使用 Steam 钱包。'),
  ('https://www.bestpartygames.net/zh', '聚会游戏推荐平台，收录适合多人聚会场景的桌游、小游戏和派对活动创意建议。'),
  ('https://www.eneba.com/zh', '欧洲数字游戏和礼品卡交易市场，提供 Steam、Xbox、PSN 等平台充值卡和游戏激活码。'),
  ('https://shop.app/', 'Shopify 推出的购物追踪应用，可统一管理所有在线订单状态，支持实时物流追踪。'),
  ('https://www.amazon.com/', '全球最大电商平台，提供海量商品的购买、快递配送及 Prime 会员增值服务。'),
  ('https://www.fiverr.com/', '全球最大的自由职业者服务平台，提供设计、写作、编程等各类数字服务的外包接单。')
)
UPDATE navigation_items
SET note = desired_notes.note
FROM desired_notes
WHERE navigation_items.url = desired_notes.url
  AND navigation_items.note IS DISTINCT FROM desired_notes.note;
